"""Generate the ``.claude/`` harness view from ``docs/development/``.

The docs are the source of the project's working knowledge — the rule cores,
the skill cores, the lessons index and each agent's role block — and the
Claude Code harness reads a GENERATED, committed copy under ``.claude/``.
The flow is one-way: the docs never depend on ``.claude/``, so any other
harness can read the same pages (plan ``harness_context_budget.md``, K7;
ruling 2026-09-19).

What generation does, per manifest entry (``tools/docs/harness_manifest.toml``):

* **rule**   — stamp + body, relative links re-pointed from the source's
  directory to the target's.
* **skill**  — the source's YAML front matter verbatim (it IS the skill's
  frontmatter), then the stamp, then the body; ``inject_error_index`` replaces
  the ``<!-- harness: error_index -->`` line with the ``!cat`` injection that
  loads ``error_index.md`` at skill-load time (harness-specific, so it lives
  here and not in the docs).
* **index**  — as ``rule``: a stamped copy that the harness does not auto-load
  (the lessons index; the session-start batch reads it).
* **agent**  — the role block is inserted into the target ``AGENT.md`` between
  ``GENERATED`` markers, after the front matter; everything else in the file
  is hand-maintained (tools, model, memory are harness-specific).
* **block**  — as ``agent``, for any hand-maintained harness file carrying a
  generated block between markers. The one target allowed outside ``.claude/``
  is the repo-root ``CLAUDE.md`` (the harness reads it there and nowhere else):
  its on-boarding block is generated from ``docs/development/onboarding.md``
  (plan ``harness_context_budget.md``, K3; ruling 2026-09-20).

Every target carries a token budget (``CHARS_PER_TOKEN``), a role block
included; exceeding it fails, because the budget is the point of the whole
arrangement. A link's
anchor is checked against the set of anchors MyST itself mints for the target
page (its own slug function, its own de-duplication, headings up to
``HEADING_ANCHOR_LEVELS``, which ``docs/conf.py`` reads from here), so the
check agrees with the docs build by construction.

Usage::

    python -m tools.docs.generate_harness            # write
    python -m tools.docs.generate_harness --check    # verify only; exit 1 on
                                                     # drift, over-budget, a
                                                     # dead link, a bad manifest
                                                     # entry, or an orphan

``--check`` is read by ``tests/test_harness_generated.py`` (the canonical pytest
gate); write mode is wired into ``docs/conf.py``'s ``_GENERATORS`` so every
Sphinx build regenerates.
"""
from __future__ import annotations

import argparse
import functools
import os
import re
import sys
import tomllib
from pathlib import Path

from markdown_it import MarkdownIt
from markdown_it.tree import SyntaxTreeNode
from myst_parser.mdit_to_docutils.base import compute_unique_slug

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "tools" / "docs" / "harness_manifest.toml"
HARNESS_DIR = REPO_ROOT / ".claude"
SLACK_MAX = 400  # a budget more than this above the measured size lets growth in unreviewed
CHARS_PER_TOKEN = 3.6  # [M] 2026-09-20: 3.51 and 3.53 chars/token on the API tokenizer, keep-minus-omit probe (plan, "T4 executed")
HEADING_ANCHOR_LEVELS = 4  # docs/conf.py: myst_heading_anchors = this
TEXT_KINDS = ("rule", "skill", "index")
BLOCK_KINDS = {"agent": "role block", "block": "block"}  # kind -> the label its markers carry
ROOT_TARGETS = (REPO_ROOT / "CLAUDE.md",)  # the targets allowed outside .claude/: the harness reads CLAUDE.md at the root
STAMP_PREFIX = "<!-- GENERATED by tools/docs/generate_harness.py from "
BEGIN_PREFIX = "<!-- BEGIN GENERATED "
BEGIN = BEGIN_PREFIX + "{label} — source: {src}; edit the source, not this block -->"
END = "<!-- END GENERATED {label} -->"
ERROR_INDEX_MARK = "<!-- harness: error_index -->"
ERROR_INDEX_LINE = (
    '!`cat "${CLAUDE_PROJECT_DIR:-.}/.claude/skills/vv-principles/error_index.md" '
    '2>/dev/null || echo "(error index unavailable — run: '
    '.venv/bin/python -m tools.verification.generate_error_index)"; exit 0`'
)
_LINK = re.compile(r"\]\((?!https?://|mailto:)([^)\s#]*)(#[^)]*)?\)")
_FRONT = re.compile(r"\A---\n.*?\n---\n", re.S)


def stamp(src: Path) -> str:
    rel = src.relative_to(REPO_ROOT).as_posix()
    return (f"{STAMP_PREFIX}{rel} — "
            f"DO NOT EDIT. Edit the source page; `python -m tools.docs.generate_harness` "
            f"(or any Sphinx build) rewrites this file. -->\n")


@functools.lru_cache(maxsize=None)
def anchors(md: Path) -> frozenset[str]:
    """The anchors MyST mints for ``md``: parsed, not regexed, so a ``#`` inside a
    fence is not a heading; slugged and de-duplicated by MyST's own function."""
    tree = SyntaxTreeNode(MarkdownIt("commonmark").parse(_FRONT.sub("", md.read_text())))
    slugs: list[str] = []
    for node in tree.children:
        if node.type == "heading" and int(node.tag[1]) <= HEADING_ANCHOR_LEVELS:
            slugs.append(compute_unique_slug(node, slugs))
    return frozenset(slugs)


def relink(body: str, src: Path, dst: Path, problems: list[str], aliases: dict[Path, Path]) -> str:
    """Re-point relative links from src's directory to dst's; every linked file must
    exist, and an anchor into a ``.md`` page must be one MyST mints for it. A link to
    a page that is itself a manifest source is written to that page's generated
    copy (``aliases``): the harness copy is the one already in an agent's context."""
    where = src.relative_to(REPO_ROOT)
    def sub(m: re.Match) -> str:
        path, anchor = m.group(1), m.group(2) or ""
        target = (src.parent / path).resolve() if path else src
        if not target.is_file():
            problems.append(f"{where}: link to missing file {path}")
            return m.group(0)
        if anchor and target.suffix == ".md" and anchor[1:] not in anchors(target):
            problems.append(f"{where}: link to missing heading {path}{anchor}")
        written = aliases.get(target, target)
        new = Path(os.path.relpath(written, dst.parent.resolve())).as_posix() if path else ""
        return f"]({new}{anchor})"
    return _LINK.sub(sub, body)


def entry_paths(entry: dict, kind: str, problems: list[str]) -> tuple[Path, Path] | None:
    """Validate one manifest entry: its keys, an existing source, a target under
    ``.claude/`` (the flow is docs -> .claude and nowhere else)."""
    required = ("source", "target", "budget_tokens")
    missing = [k for k in required if k not in entry]
    label = entry.get("target") or entry.get("source") or "?"
    if missing:
        problems.append(f"[[{kind}]] {label}: missing {', '.join(missing)}")
        return None
    src, dst = REPO_ROOT / entry["source"], REPO_ROOT / entry["target"]
    if not src.is_file():
        problems.append(f"[[{kind}]] {label}: source {entry['source']} does not exist")
        return None
    if not dst.resolve().is_relative_to(HARNESS_DIR) and dst.resolve() not in ROOT_TARGETS:
        problems.append(f"[[{kind}]] {label}: a target must lie under .claude/ (the repo-root CLAUDE.md excepted)")
        return None
    return src, dst


def render_text(entry: dict, kind: str, problems: list[str], aliases: dict[Path, Path]) -> tuple[Path, str] | None:
    paths = entry_paths(entry, kind, problems)
    if paths is None:
        return None
    src, dst = paths
    text = src.read_text()
    front = ""
    if kind == "skill":
        m = _FRONT.match(text)
        if not m:
            problems.append(f"{src.relative_to(REPO_ROOT)}: a skill source needs YAML front matter")
        else:
            front, text = m.group(0), text[m.end():]
    else:
        text = _FRONT.sub("", text)
    body = relink(text, src, dst, problems, aliases)
    if entry.get("inject_error_index"):
        if ERROR_INDEX_MARK not in body:
            problems.append(f"{src.relative_to(REPO_ROOT)}: inject_error_index set but {ERROR_INDEX_MARK} absent")
        body = body.replace(ERROR_INDEX_MARK, ERROR_INDEX_LINE)
    out = front + stamp(src) + body.lstrip("\n")
    tokens = int(len(out) / CHARS_PER_TOKEN)
    if tokens > entry["budget_tokens"]:
        problems.append(f"{dst.relative_to(REPO_ROOT)}: ≈{tokens} tokens > budget {entry['budget_tokens']}")
    elif entry["budget_tokens"] - tokens > SLACK_MAX:
        problems.append(f"{dst.relative_to(REPO_ROOT)}: budget {entry['budget_tokens']} is {entry['budget_tokens'] - tokens} tokens above ≈{tokens}, more than SLACK_MAX {SLACK_MAX}; lower it")
    return dst, out


def render_block(entry: dict, kind: str, problems: list[str], aliases: dict[Path, Path]) -> tuple[Path, str] | None:
    """A generated block between markers inside a hand-maintained file — an AGENT.md's
    role block, CLAUDE.md's on-boarding block; everything outside the markers is kept."""
    paths = entry_paths(entry, kind, problems)
    if paths is None:
        return None
    src, dst = paths
    label = BLOCK_KINDS[kind]
    begin = BEGIN.format(label=label, src=src.relative_to(REPO_ROOT).as_posix())
    end = END.format(label=label)
    rel_dst = dst.relative_to(REPO_ROOT)
    block = relink(_FRONT.sub("", src.read_text()).strip("\n"), src, dst, problems, aliases)
    generated = f"{begin}\n{block}\n{end}\n"
    tokens = int(len(generated) / CHARS_PER_TOKEN)
    if tokens > entry["budget_tokens"]:
        problems.append(f"{rel_dst}: {label} ≈{tokens} tokens > budget {entry['budget_tokens']}")
    elif entry["budget_tokens"] - tokens > SLACK_MAX:
        problems.append(f"{rel_dst}: {label} budget {entry['budget_tokens']} is {entry['budget_tokens'] - tokens} tokens above ≈{tokens}, more than SLACK_MAX {SLACK_MAX}; lower it")
    current = dst.read_text() if dst.exists() else ""
    i = current.find(BEGIN_PREFIX + label)
    if i >= 0:
        j = current.find(end, i)
        if j < 0:
            problems.append(f"{rel_dst}: BEGIN marker without END")
            return dst, current
        return dst, current[:i] + generated + current[j + len(end) + 1:]
    if end in current:
        problems.append(f"{rel_dst}: END marker without BEGIN")
        return dst, current
    if block.split("\n", 1)[0] in current:  # the source's own H1 line, present without its markers
        problems.append(f"{rel_dst}: the {label} is present without its markers; "
                        "restore the markers or delete the stale block (regenerating would duplicate it)")
        return dst, current
    m = _FRONT.match(current)
    if not m:
        problems.append(f"{rel_dst}: no front matter to insert the {label} after; place the markers by hand")
        return dst, current
    return dst, current[:m.end()] + "\n" + generated + current[m.end():].lstrip("\n")


def render_all(manifest: dict) -> tuple[dict[Path, str], list[str]]:
    anchors.cache_clear()
    problems: list[str] = []
    outputs: dict[Path, str] = {}
    aliases = {(REPO_ROOT / e["source"]).resolve(): (REPO_ROOT / e["target"]).resolve()
               for kind in TEXT_KINDS for e in manifest.get(kind, []) if "source" in e and "target" in e}
    for kind in TEXT_KINDS:
        for entry in manifest.get(kind, []):
            if (rendered := render_text(entry, kind, problems, aliases)) is not None:
                outputs[rendered[0]] = rendered[1]
    for kind in BLOCK_KINDS:
        for entry in manifest.get(kind, []):
            if (rendered := render_block(entry, kind, problems, aliases)) is not None:
                outputs[rendered[0]] = rendered[1]
    return outputs, problems


def orphans(outputs: dict[Path, str]) -> list[str]:
    """Files under the harness, and the root targets, carrying the stamp or a block
    marker at column 0 that no manifest entry produces any more (a linked worktree
    is another checkout)."""
    stamped = re.compile(rf"(?m)^(?:{re.escape(STAMP_PREFIX)}|{re.escape(BEGIN_PREFIX)})")
    candidates = [p for p in HARNESS_DIR.rglob("*.md") if "worktrees" not in p.relative_to(HARNESS_DIR).parts]
    candidates += [p for p in ROOT_TARGETS if p.exists()]
    return [f"{p.relative_to(REPO_ROOT)}: carries a GENERATED stamp but no manifest entry produces it"
            for p in candidates if p not in outputs and stamped.search(p.read_text())]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift/problems")
    args = ap.parse_args(argv)
    manifest = tomllib.loads(MANIFEST.read_text())
    outputs, problems = render_all(manifest)
    problems += orphans(outputs)
    drift = [p for p, out in outputs.items() if not p.exists() or p.read_text() != out]
    if args.check:
        for p in problems:
            print(f"PROBLEM: {p}")
        for p in drift:
            print(f"DRIFT: {p.relative_to(REPO_ROOT)} differs from its source (run the generator)")
        print(f"harness: {len(outputs)} targets, {len(problems)} problems, {len(drift)} drifted")
        return 0 if not problems and not drift else 1
    if problems:
        for p in problems:
            print(f"PROBLEM: {p}", file=sys.stderr)
        return 1
    for p, out in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(out)
    print(f"harness: wrote {len(outputs)} targets ({len(drift)} changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
