"""Generate the ``.claude/`` harness view from ``docs/development/``.

The docs are the source of the project's working knowledge — the rule cores,
the skill cores, the lessons index and each agent's role block — and the
Claude Code harness reads a GENERATED, committed copy under ``.claude/``.
The flow is one-way: the docs never depend on ``.claude/``, so any other
harness can read the same pages (plan ``harness_context_budget.md``, K7;
ruling 2026-09-19).

What generation does, per manifest entry (``tools/docs/harness_manifest.toml``):

* **rule**   — stamp + body, relative links re-pointed from the source's
  directory to the target's.
* **skill**  — the source's YAML front matter verbatim (it IS the skill's
  frontmatter), then the stamp, then the body; ``inject_error_index`` replaces
  the ``<!-- harness: error_index -->`` line with the ``!cat`` injection that
  loads ``error_index.md`` at skill-load time (harness-specific, so it lives
  here and not in the docs).
* **index**  — as ``rule`` (the lessons index).
* **agent**  — the role block is inserted into the target ``AGENT.md`` between
  ``GENERATED`` markers, after the front matter; everything else in the file
  is hand-maintained (tools, model, memory are harness-specific).

Every text target has a token budget (chars / 3.6); exceeding it fails, because
the budget is the point of the whole arrangement.

Usage::

    python -m tools.docs.generate_harness            # write
    python -m tools.docs.generate_harness --check    # verify: exit 1 on drift,
                                                     # over-budget, or a link to
                                                     # a heading that does not exist

Wired into ``docs/conf.py``'s ``_GENERATORS`` so every Sphinx build regenerates.
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "tools" / "docs" / "harness_manifest.toml"
CHARS_PER_TOKEN = 3.6
BEGIN = "<!-- BEGIN GENERATED role block — source: {src}; edit the source, not this block -->"
END = "<!-- END GENERATED role block -->"
ERROR_INDEX_MARK = "<!-- harness: error_index -->"
ERROR_INDEX_LINE = (
    '!`cat "${CLAUDE_PROJECT_DIR:-.}/.claude/skills/vv-principles/error_index.md" '
    '2>/dev/null || echo "(error index unavailable — run: '
    '.venv/bin/python -m tools.verification.generate_error_index)"; exit 0`'
)
_LINK = re.compile(r"\]\(([^)\s#]+\.md)(#[^)]*)?\)")
_FRONT = re.compile(r"\A---\n.*?\n---\n", re.S)
_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$", re.M)


def stamp(src: Path) -> str:
    rel = src.relative_to(REPO_ROOT).as_posix()
    return (f"<!-- GENERATED by tools/docs/generate_harness.py from {rel} — "
            f"DO NOT EDIT. Edit the source page; `python -m tools.docs.generate_harness` "
            f"(or any Sphinx build) rewrites this file. -->\n")


def myst_slug(text: str) -> str:
    """MyST's ``myst_heading_anchors`` slug: lowercase, spaces → '-', drop the rest."""
    text = re.sub(r"`([^`]*)`", r"\1", text)  # inline code contributes its text
    s = text.strip().lower().replace(" ", "-")
    return re.sub(r"[^a-z0-9\-_]", "", s)


def headings(md: Path) -> set[str]:
    body = _FRONT.sub("", md.read_text())
    seen: dict[str, int] = {}
    out: set[str] = set()
    for m in _HEADING.finditer(body):
        slug = myst_slug(m.group(2))
        n = seen.get(slug, 0)
        out.add(slug if n == 0 else f"{slug}-{n}")
        seen[slug] = n + 1
    return out


def relink(body: str, src: Path, dst: Path, problems: list[str]) -> str:
    """Re-point relative ``.md`` links from src's directory to dst's; check anchors."""
    def sub(m: re.Match) -> str:
        rel, anchor = m.group(1), m.group(2) or ""
        target = (src.parent / rel).resolve()
        if not target.exists():
            problems.append(f"{src.name}: link to missing file {rel}")
            return m.group(0)
        if anchor and anchor[1:] not in headings(target):
            problems.append(f"{src.name}: link to missing heading {rel}{anchor}")
        try:
            new = Path(target).relative_to(dst.parent.resolve()).as_posix()
        except ValueError:
            new = Path(*([".."] * len(dst.parent.resolve().relative_to(REPO_ROOT).parts)),
                       *target.relative_to(REPO_ROOT).parts).as_posix()
        return f"]({new}{anchor})"
    return _LINK.sub(sub, body)


def render_text(entry: dict, kind: str, problems: list[str]) -> tuple[Path, str]:
    src = REPO_ROOT / entry["source"]
    dst = REPO_ROOT / entry["target"]
    text = src.read_text()
    front = ""
    if kind == "skill":
        m = _FRONT.match(text)
        if not m:
            problems.append(f"{src.name}: a skill source needs YAML front matter")
        else:
            front, text = m.group(0), text[m.end():]
    else:
        text = _FRONT.sub("", text)
    body = relink(text, src, dst, problems)
    if entry.get("inject_error_index"):
        if ERROR_INDEX_MARK not in body:
            problems.append(f"{src.name}: inject_error_index set but {ERROR_INDEX_MARK} absent")
        body = body.replace(ERROR_INDEX_MARK, ERROR_INDEX_LINE)
    out = front + stamp(src) + body.lstrip("\n")
    budget = entry.get("budget_tokens")
    if budget is not None:
        tokens = int(len(out) / CHARS_PER_TOKEN)
        if tokens > budget:
            problems.append(f"{dst.relative_to(REPO_ROOT)}: ≈{tokens} tokens > budget {budget}")
    return dst, out


def render_agent(entry: dict, problems: list[str]) -> tuple[Path, str]:
    src = REPO_ROOT / entry["source"]
    dst = REPO_ROOT / entry["target"]
    block = relink(_FRONT.sub("", src.read_text()).strip("\n"), src, dst, problems)
    rel = src.relative_to(REPO_ROOT).as_posix()
    generated = f"{BEGIN.format(src=rel)}\n{block}\n{END}\n"
    current = dst.read_text() if dst.exists() else ""
    begin_line = BEGIN.split(" — ")[0]
    if begin_line in current:
        i = current.index(begin_line)
        j = current.index(END, i) + len(END) + 1
        out = current[:i] + generated + current[j:]
    else:
        m = _FRONT.match(current)
        if not m:
            problems.append(f"{dst.relative_to(REPO_ROOT)}: no front matter to insert after")
            return dst, current
        out = current[:m.end()] + "\n" + generated + current[m.end():].lstrip("\n")
    return dst, out


def render_all(manifest: dict) -> tuple[dict[Path, str], list[str]]:
    problems: list[str] = []
    outputs: dict[Path, str] = {}
    for kind in ("rule", "skill", "index"):
        for entry in manifest.get(kind, []):
            dst, out = render_text(entry, kind, problems)
            outputs[dst] = out
    for entry in manifest.get("agent", []):
        dst, out = render_agent(entry, problems)
        outputs[dst] = out
    return outputs, problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift/problems")
    args = ap.parse_args(argv)
    manifest = tomllib.loads(MANIFEST.read_text())
    outputs, problems = render_all(manifest)
    drift = [p for p, out in outputs.items() if not p.exists() or p.read_text() != out]
    if args.check:
        for p in problems:
            print(f"PROBLEM: {p}")
        for p in drift:
            print(f"DRIFT: {p.relative_to(REPO_ROOT)} differs from its source (run the generator)")
        ok = not problems and not drift
        print(f"harness: {len(outputs)} targets, {len(problems)} problems, {len(drift)} drifted")
        return 0 if ok else 1
    if problems:
        for p in problems:
            print(f"PROBLEM: {p}", file=sys.stderr)
        return 1
    for p, out in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(out)
    print(f"harness: wrote {len(outputs)} targets ({len(drift)} changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
