#!/usr/bin/env python3
"""PreToolUse hook on Edit, Write and MultiEdit: refuses a hand edit of generated text, for the
main agent and every sub-agent alike (a settings.json hook fires inside sub-agents too).

Generated text comes in two shapes (the harness page, "The one-way flow"). A WHOLE FILE carries a
stamp in its first lines, ``<!-- GENERATED by <generator> from <source> — DO NOT EDIT``: every edit
of it is refused. A BLOCK sits between ``<!-- BEGIN GENERATED <label> — source: <source>; …-->`` and
``<!-- END GENERATED <label> -->`` inside a hand-maintained file (an AGENT.md's definition below its
front matter, CLAUDE.md's on-boarding block, the brief-rules list on the workflows page): an edit that
changes a block is refused, and one elsewhere in the file passes. A file an installer recorded in a
``.claude/*-install-manifest.json`` is refused too: it is the installer's to update.

The refusal names the source and the command that regenerates. Not seen, stated so a pass is read
for what it is: a write through Bash (``sed -i``, a heredoc, a script), which the drift check of
``python -m tools.harness --check`` catches in CI instead; this hook is the early refusal, not the only
one. Exit 2 blocks the call and hands the reason back; anything else lets it through. The payload
arrives on stdin as JSON (``tool_name``, ``tool_input``, ``cwd``).
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

STAMP = re.compile(r"<!-- GENERATED by (\S+?)(?: from (\S+))? —")
BEGIN = re.compile(r"<!-- BEGIN GENERATED (.+?) — source: ([^;]+);[^\n]*-->")
REGENERATE = "`.venv/bin/python -m tools.harness`"


def blocks(text: str) -> list[tuple[int, int, str, str]]:
    """Every generated block: (start, end, label, source), markers included."""
    found = []
    for m in BEGIN.finditer(text):
        end_marker = f"<!-- END GENERATED {m.group(1)} -->"
        j = text.find(end_marker, m.end())
        found.append((m.start(), len(text) if j < 0 else j + len(end_marker), m.group(1), m.group(2).strip()))
    return found


def block_texts(text: str) -> dict[str, str]:
    return {label: text[a:b] for a, b, label, _ in blocks(text)}


def installed(project: Path, path: Path) -> str | None:
    for manifest in (project / ".claude").glob("*-install-manifest.json"):
        try:
            files = json.loads(manifest.read_text(encoding="utf-8")).get("files") or {}
        except Exception:
            continue
        if any((project / ".claude" / key).resolve() == path for key in files):
            return manifest.name.split("-", 1)[0]
    return None


def refusal(path: Path, text: str, tool: str, tool_input: dict) -> str | None:
    head = STAMP.search(text[:1200])
    if head:
        source = head.group(2) or "its generator's input"
        return (f"generated-guard: {path.name} is GENERATED by {head.group(1)} from {source}; a hand edit is "
                f"drift that --check and CI reject. Edit {source}, then run {REGENERATE}.")
    spans = blocks(text)
    if not spans:
        return None
    touched: list[tuple[str, str]] = []
    if tool == "Write":
        new = block_texts(tool_input.get("content") or "")
        touched = [(label, source) for _, _, label, source in spans
                   if new.get(label) != block_texts(text).get(label)]
    else:
        edits = tool_input.get("edits") if tool == "MultiEdit" else [tool_input]
        for edit in edits or []:
            old = edit.get("old_string") or ""
            for m in re.finditer(re.escape(old), text) if old else []:
                touched += [(label, source) for a, b, label, source in spans if m.start() < b and m.end() > a]
    if not touched:
        return None
    label, source = touched[0]
    return (f"generated-guard: this edit changes the GENERATED {label} of {path.name}, whose source is "
            f"{source}. Edit the source, then run {REGENERATE}; text outside the markers is hand-maintained.")


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0
    tool = payload.get("tool_name")
    if tool not in {"Edit", "Write", "MultiEdit"}:
        return 0
    tool_input = payload.get("tool_input") or {}
    raw = tool_input.get("file_path") or ""
    if not raw:
        return 0
    project = Path(os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or ".").resolve()
    path = (project / raw).resolve() if not os.path.isabs(raw) else Path(raw).resolve()
    if who := installed(project, path):
        print(f"generated-guard: {path.name} was installed by {who} and is recorded in its manifest; an edit "
              f"here is a fork the installer cannot update. Change it upstream and re-run the installer.",
              file=sys.stderr)
        return 2
    if not path.is_file():
        return 0
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return 0
    if reason := refusal(path, text, tool, tool_input):
        print(reason, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
