r"""TESTS-FIRST equivalence harness for the 2-D octant sweep refactor.

This file is the C2.5 gate of Wave 2 of the SN-performance plan
(``transient-giggling-cake.md``).  It pins the **per-sweep semantic
contract** of :func:`orpheus.sn.sweep._sweep_2d_wavefront` against
frozen-reference snapshots captured **from the legacy (still
loop-based) implementation** before the refactor lands.

Architectural context
=====================

Wave 2 replaces the inner ``for n in range(N)`` loop in
:func:`_sweep_2d_wavefront` with a per-octant ``SweepDependencyGraph``
that vectorises the ordinate axis internally::

    legacy:                              new:
    for n in range(N):                   for octant in quad.octants:
        BC apply for n                       BC apply ONCE per octant
        for diag in diags:                   sweep_graph.apply(...)
            DD update                        # vectorised over (N_oct, n_diag, ng)
            scalar_flux += w[n] * psi_avg

The harness MUST detect every wrong-but-plausible regression the new
architecture creates.  The seven failure modes designed for here map
onto :doc:`/.claude/skills/vv-principles/SKILL.md` AI failure modes
1-6 + the L7 BC-apply-once-per-octant trap that the architecture
itself creates:

1. **L7-trap (BC-apply-once-per-octant).**  Legacy code re-applies BC
   per ordinate.  New code applies BC once per octant.  If the new
   code accidentally re-applies BCs at every topological level (or at
   every ordinate within an octant), the **reflective-BC** boundary
   buffers get over-written and the sweep output drifts.  Surfaced by
   case 3 (mixed reflective + vacuum BCs with non-zero initial
   reflective-buffer content — the L7 mode is invisible if both
   buffers start at zero).
2. **Per-octant anti-diagonal coverage.**  Every cell visited exactly
   once per octant.  Surfaced by every case (the bit-identity
   contract requires it).
3. **Pure-z ordinate handling.**  Ordinates with
   ``|μ_x| < 1e-15 AND |μ_y| < 1e-15`` (Lebedev order 5 has two:
   ``(0,0,±1)``).  Surfaced by case 6.
4. **Multi-group + heterogeneous (vv-principles anti-pattern #4).**
   Flat flux nulls every redistribution and weight-cancellation term;
   asymmetric multi-group + heterogeneous is the canonical stressor.
   Surfaced by cases 3, 4, 5.
5. **Q_aniso branch.**  Per-ordinate anisotropic source.  Surfaced by
   case 5.
6. **Reduction-tree drift.**  ``np.einsum("nh,n->h", ...)`` reduction
   order vs the legacy ``for n: scalar_flux += w[n] * psi[n]``.  Drift
   bounded by ``N × ULP``; for the worst case here (Lebedev order 5,
   N=14) ≤ ~1e-15.  Tolerance pinned to ``nulp=64`` (worst-case
   ~1.4e-14) for the bit-identity-class assertions.
7. **Quadrature-dependent normalisation (Signature 4 / ERR-004 /
   ERR-025).**  ``Σ w`` differs across quadrature families.  Surfaced
   by case 7 (closed-form anchor: φ = Q/Σ_t under all-reflective +
   uniform Q + uniform Σ_t for ANY quadrature whose ``Σ w`` matches
   the convention used in the sweep's ``weight_norm`` factor).

Snapshot generation
===================

Snapshots live at ``tests/sn/regression/snapshots/
2d_octant_equivalence_<case_id>.npz``.  They are generated by
:mod:`tests.sn.regression._generate_2d_octant_snapshots` against the
LEGACY implementation, then frozen in the repo.  This test file
re-runs each case against whatever implementation is currently in
``orpheus.sn.sweep`` and asserts bit-for-bit (within ``nulp=64``)
agreement.

Generation protocol::

    # On the LEGACY commit (BEFORE the refactor lands):
    python -m tests.sn.regression._generate_2d_octant_snapshots
    # Commit the snapshots.
    # On the refactor branch: this test re-runs each case and gates
    # the refactor against bit-equality with the snapshots.

Tolerance choices
=================

* Snapshot-bit-identity cases (1-6): ``nulp=64``.  Worst case is
  Lebedev order 5 (N=14); reduction-tree drift is ``N × ULP ≈ 14 ×
  2.22e-16 ≈ 3.1e-15``.  ``nulp=64`` (~1.4e-14) absorbs this with a
  ~4× margin while still catching any algorithmic drift > N × ULP.
* Closed-form anchor (case 7): ``rtol=1e-14, atol=0``.  Reflective +
  uniform Q + uniform Σ_t makes φ = Q/Σ_t exact under DD; the
  iterative-solver convergence floor governs (the sweep alone does
  NOT converge to the equilibrium — only ``solve_sn_fixed_source``
  does, so case 7 is asserted on the converged value).

The L1 closed-form anchor (case 7) is what makes this harness more
than a self-consistency gate: it provides structurally-independent
grounding (an analytical reference, not an inheritance from the
legacy code).  Cases 1-6 are L1 + regression (regressions are
inheritance from the legacy implementation; case 7 is the
analytical anchor that proves the legacy implementation was itself
correct on at least one verified configuration).

V&V tags
========

Per :doc:`/.claude/skills/vv-principles/SKILL.md`:

* ``@pytest.mark.l1`` — equation-level claim (sum-of-tensor-products
  streaming form, §15A.2).  Closed-form anchor case 7 grounds this
  with an analytical reference; bit-identity cases 1-6 inherit
  from the verified legacy code.
* ``@pytest.mark.regression`` — opt-in gate that runs only when SN
  module files are touched (matches existing snapshot tests).
* ``@pytest.mark.catches("ERR-003")`` — case 3's mixed-BC mode
  reproduces the ERR-003 failure family (reflective-BC ordering
  drift under ordinate batching).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import numpy as np
import pytest

from orpheus.derivations.common.xs_library import get_mixture
from orpheus.geometry import BC, Mesh2D
from orpheus.sn.boundary_flux import BoundaryFlux
from orpheus.sn.geometry import SNMesh
from orpheus.sn.quadrature import LebedevSphere, LevelSymmetricSN
from orpheus.sn.solver import solve_sn_fixed_source
from orpheus.sn.sweep import _sweep_2d_wavefront
from tests.sn._test_helpers import placeholder_materials


# File-level marker: every case is an L1 equation-equivalence claim
# on the 2-D wavefront sweep.
pytestmark = pytest.mark.l1


SNAPSHOT_DIR = Path(__file__).parent / "regression" / "snapshots"
"""Snapshot location.  Snapshots are .npz files keyed by case id::

    snapshots/2d_octant_equivalence_<case_id>.npz

with payload keys (Issue #196 PR-INDEX-5 — principled layout):

* ``angular_flux`` — ``(N, ng, nx, ny)`` float64
* ``scalar_flux`` — ``(ng, nx, ny)`` float64
* ``psi_x_post`` — ``(N, ng, nx+1, ny)`` float64 (post-sweep BC buffer)
* ``psi_y_post`` — ``(N, ng, nx, ny+1)`` float64 (post-sweep BC buffer)
* ``case_id`` — string
* ``case_description`` — string
* ``generator_commit`` — short SHA
"""

# ═══════════════════════════════════════════════════════════════════
# Setup helpers — small Cartesian SNMesh factory
# ═══════════════════════════════════════════════════════════════════
#
# Inheritance: the BC / Mesh2D / quadrature primitives are the same
# fixtures used by ``test_unified_sweep_dispatch.py`` and
# ``test_snstreamingoperator.py::test_apply_2d_cartesian_bit_identical_to_legacy``.
# That gives the harness a known-good starting point.


def _build_2d_mesh(
    nx: int,
    ny: int,
    bc_xmin: str,
    bc_xmax: str,
    bc_ymin: str,
    bc_ymax: str,
    *,
    n_materials: int = 1,
) -> Mesh2D:
    """Build a small Cartesian Mesh2D with configurable BCs and materials.

    For ``n_materials == 2`` the mesh splits roughly in half along the
    x-axis: ``mat_map[i, j] = 0`` for ``i < nx // 2`` else ``1``.  This
    is the canonical heterogeneous fingerprint — the asymmetry stresses
    the redistribution / scattering-source convention drift modes that
    a homogeneous case nulls out.
    """
    if n_materials == 1:
        mat_map = np.zeros((nx, ny), dtype=int)
    elif n_materials == 2:
        mat_map = np.zeros((nx, ny), dtype=int)
        mat_map[nx // 2:, :] = 1
    else:
        raise ValueError(f"n_materials must be 1 or 2; got {n_materials}")

    return Mesh2D(
        edges_x=np.linspace(0.0, 1.0, nx + 1),
        edges_y=np.linspace(0.0, 1.0, ny + 1),
        mat_map=mat_map,
        bc_xmin=BC(bc_xmin),
        bc_xmax=BC(bc_xmax),
        bc_ymin=BC(bc_ymin),
        bc_ymax=BC(bc_ymax),
    )


def _build_sn_mesh(
    nx: int = 3,
    ny: int = 3,
    bc_xmin: str = "vacuum",
    bc_xmax: str = "vacuum",
    bc_ymin: str = "vacuum",
    bc_ymax: str = "vacuum",
    quadrature: str = "LS4",
    n_materials: int = 1,
    ng: int = 1,
) -> SNMesh:
    """Build a 3×3 Cartesian SNMesh wired for the 2-D wavefront sweep."""
    mesh = _build_2d_mesh(
        nx, ny,
        bc_xmin=bc_xmin, bc_xmax=bc_xmax,
        bc_ymin=bc_ymin, bc_ymax=bc_ymax,
        n_materials=n_materials,
    )
    if quadrature == "LS4":
        quad = LevelSymmetricSN.create(sn_order=4)            # N = 24
    elif quadrature == "LS6":
        quad = LevelSymmetricSN.create(sn_order=6)            # N = 48
    elif quadrature == "Lebedev5":
        # Lebedev order 5 has two pure-z ordinates (n=4: (0,0,+1),
        # n=5: (0,0,-1)).  This is the only ORPHEUS quadrature in this
        # harness's roster that exhibits the ``sign_x == 0 == sign_y``
        # degenerate-ordinate path.
        quad = LebedevSphere.create(order=5)                  # N = 14
    else:
        raise ValueError(f"Unknown quadrature kind: {quadrature}")
    return SNMesh(
        mesh, quad,
        placeholder_materials(ng=ng, mat_ids=tuple(range(n_materials))),
    )


def _build_sig_t(
    sn_mesh: SNMesh, materials: dict, ng: int,
) -> np.ndarray:
    """Build the per-cell per-group ``sig_t`` array from a materials dict.

    Issue #196 PR-INDEX-4: principled ``(ng, nx, ny)`` layout to match
    ``_sweep_2d_wavefront``'s direct contract.
    """
    nx, ny = sn_mesh.nx, sn_mesh.ny
    sig_t = np.zeros((ng, nx, ny))
    for mid, mix in materials.items():
        cells = sn_mesh.mat_map == mid
        # ``Mixture.SigT`` is ``(ng,)``.  Broadcast across spatial axes.
        # sig_t[:, cells] expects shape (ng, n_cells); SigT[:, None]
        # broadcasts across the cells dimension.
        sig_t[:, cells] = mix.SigT[:, None]
    return sig_t


def _empty_boundary_flux(sn_mesh: SNMesh) -> "BoundaryFlux":
    """Fresh zero :class:`BoundaryFlux`; the sweep populates buffers on first call.

    Issue #197 PR-TYPED-2 — typed replacement for the legacy
    ``psi_bc: dict`` fixture pattern.
    """
    return sn_mesh.zeros_boundary_flux()


# ═══════════════════════════════════════════════════════════════════
# Case registry — every parametrised case the harness exercises
# ═══════════════════════════════════════════════════════════════════


@dataclass(frozen=True)
class OctantEquivalenceCase:
    """One entry in the 2-D octant-sweep equivalence harness."""

    case_id: str
    """Snapshot file basename (``snapshots/2d_octant_equivalence_<case_id>.npz``)."""

    description: str
    """One-line description for the snapshot metadata."""

    failure_mode: str
    """The vv-principles AI failure mode # (1-7) this row gates against."""

    builder: Callable[[], "OctantEquivalenceInputs"]
    """Builder closure producing the SNMesh + Q + Q_aniso + psi_bc."""

    nulp: int = 64
    """Tolerance budget — see file docstring."""

    n_sweeps: int = 1
    """Number of consecutive sweeps to run (sharing psi_bc).

    L7-trap detection (case 3, case 5) uses ``n_sweeps=2``: the first
    sweep equilibrates the reflective-BC buffer, the second sweep then
    READS the equilibrated buffer at BC application time.  If a
    refactor accidentally re-applies BCs per topological level, the
    second sweep's BC-buffer reads will diverge from the legacy
    once-per-ordinate read pattern, surfacing as drift in the
    second-sweep outputs.

    Single-sweep cases would NOT detect L7-bugs in this codebase
    because the legacy sweep's per-ordinate ``BC.apply`` happens at
    the very start of each ordinate's iteration, before the buffer
    has been written by anything in the current sweep — so seeding
    pre-sweep is overwritten by the same-sweep flow.  Only the
    second sweep can read what the first sweep wrote.
    """


@dataclass(frozen=True)
class OctantEquivalenceInputs:
    """Per-case inputs to ``_sweep_2d_wavefront``.

    Issue #196 PR-INDEX-4: principled ``(ng, nx, ny)`` for the scalar
    source ``Q`` and the cross-section ``sig_t``; principled
    ``(N, ng, nx, ny)`` for the optional anisotropic source.

    Issue #197 PR-TYPED-4: field renamed ``Q_aniso → aniso_source``
    to align with the typed-source vocabulary; the field still carries
    a bare ndarray because the consumer is the INTERNAL
    ``_sweep_2d_wavefront`` which keeps its bare-ndarray signature
    (the public typed contract lives at :func:`transport_sweep`).
    """

    sn_mesh: SNMesh
    Q: np.ndarray                          # (ng, nx, ny) — isotropic source
    sig_t: np.ndarray                      # (ng, nx, ny)
    boundary_flux: "BoundaryFlux"         # mutable — sweep mutates BC buffers
    aniso_source: np.ndarray | None = None  # (N, ng, nx, ny) or None


# ─── case-1 — smoke (all-vacuum, 1G homogeneous, uniform Q) ──────────


def _case_1_smoke() -> OctantEquivalenceInputs:
    """Vacuum BCs, 1G, homogeneous, uniform Q.

    Failure mode coverage: #2 per-octant anti-diagonal coverage —
    if the new code misses or double-counts a cell, the bit-identity
    contract fails on this trivial baseline.  This is the lowest-risk
    case; if it fails, everything downstream fails.
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="vacuum", bc_xmax="vacuum",
        bc_ymin="vacuum", bc_ymax="vacuum",
        quadrature="LS4", n_materials=1,
    )
    materials = {0: get_mixture("A", "1g")}
    sig_t = _build_sig_t(sn_mesh, materials, ng=1)
    # PR-INDEX-4: principled (ng, nx, ny).
    Q = np.ones((1, sn_mesh.nx, sn_mesh.ny))
    return OctantEquivalenceInputs(
        sn_mesh=sn_mesh, Q=Q, sig_t=sig_t,
        boundary_flux=sn_mesh.zeros_boundary_flux(), aniso_source=None,
    )


# ─── case-2 — all-reflective, 1G homogeneous, uniform Q ──────────────


def _case_2_reflective() -> OctantEquivalenceInputs:
    """All-reflective BCs, 1G homogeneous, uniform Q (TWO sweeps).

    Failure mode coverage: BC-apply-once-per-octant on a
    reflective-only boundary.  Unlike case 3 (mixed BC, fixed-points
    in 1 sweep), the all-reflective configuration does NOT reach a
    fixed point in 1 sweep — the second sweep's ``scalar_flux`` is
    measurably different (~0.4 in absolute magnitude in this
    configuration) from the first sweep's because every face is
    reflective and the iteration accumulates flux globally.  This
    makes BOTH ``scalar_flux`` AND ``psi_x_post`` / ``psi_y_post``
    sensitive to L7-trap regressions on this case.
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="reflective", bc_xmax="reflective",
        bc_ymin="reflective", bc_ymax="reflective",
        quadrature="LS4", n_materials=1,
    )
    materials = {0: get_mixture("A", "1g")}
    sig_t = _build_sig_t(sn_mesh, materials, ng=1)
    Q = np.ones((1, sn_mesh.nx, sn_mesh.ny))
    return OctantEquivalenceInputs(
        sn_mesh=sn_mesh, Q=Q, sig_t=sig_t,
        boundary_flux=_empty_boundary_flux(sn_mesh), aniso_source=None,
    )


# ─── case-3 — L7-TRAP — mixed BC, 2G asymmetric, heterogeneous ──────


def _case_3_l7_trap() -> OctantEquivalenceInputs:
    """Mixed BC (refl L+B, vac R+T), 2G asymmetric, heterogeneous.

    Failure mode coverage: L7-TRAP detection via the ``psi_x_post`` /
    ``psi_y_post`` bit-identity assertions on a mixed-BC,
    multi-material, multi-group configuration.  Specifically:

    The wavefront sweep on this configuration reaches a fixed point
    in 1 sweep — the ``scalar_flux`` is deterministic on the FIRST
    sweep call regardless of psi_bc state, because intra-sweep
    ordinate ordering already gives forward-x access to backward-x's
    converged outgoing flux.  However the **post-sweep** psi_bc state
    IS sensitive to BC-application ordering: a refactor that applies
    BC for an octant BEFORE the octant containing the reflected
    ordinate has been processed would read uninitialized (zero) face
    flux instead of the legacy "post-reflected-ordinate" flux,
    yielding a different ``psi_x_post`` / ``psi_y_post``.  The
    snapshot assertions on those two buffers are therefore the
    primary L7-trap detector for case 3.

    Two-sweep design (``n_sweeps=2``): the second sweep AMPLIFIES any
    BC-ordering drift across iterations — the post-2nd-sweep buffer
    state will diverge by an order of magnitude more than the
    post-1st-sweep state if the bug is present.  This makes the
    nulp-tolerant snapshot comparison robust: the bit-identity gate
    (within ``nulp=64``) cannot be defeated by an O(rounding) drift.

    Also catches:
      * AI failure mode #6 (convention drift on SigS) — 2G
        asymmetric scattering matrix surfaces a ``SigS`` vs
        ``SigS^T`` swap as different ``angular_flux``.
      * AI failure mode #4 (multi-group + heterogeneous) — ``A`` /
        ``B`` mixture split makes Σ_t spatially varying, asymmetric
        scattering coupling.
      * ERR-003 (reflective-BC ordering coupled with ordinate
        batching).  ERR-003 was the original case where octant
        batching changed reflective-BC update ordering and broke 2G
        convergence; the L7-trap is the structural successor.
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="reflective", bc_xmax="vacuum",
        bc_ymin="reflective", bc_ymax="vacuum",
        quadrature="LS4", n_materials=2, ng=2,
    )
    materials = {0: get_mixture("A", "2g"), 1: get_mixture("B", "2g")}
    sig_t = _build_sig_t(sn_mesh, materials, ng=2)
    # Spatially uniform Q to keep the assertion focused on the BC /
    # heterogeneity / multi-group axes.  Uniform-Q + heterogeneous Σ_t
    # is the canonical fingerprint that surfaces redistribution bugs
    # on a flat-source baseline.  PR-INDEX-4 (ng, nx, ny).
    Q = np.ones((2, sn_mesh.nx, sn_mesh.ny))
    return OctantEquivalenceInputs(
        sn_mesh=sn_mesh, Q=Q, sig_t=sig_t,
        boundary_flux=_empty_boundary_flux(sn_mesh), aniso_source=None,
    )


# ─── case-4 — vacuum + 2G asymmetric heterogeneous + gradient Q ──────


def _case_4_heterogeneous() -> OctantEquivalenceInputs:
    """Vacuum BCs, gradient Q, 2G asymmetric, heterogeneous, LS6.

    Failure mode coverage: AI failure mode #4 (multi-group +
    heterogeneous, vv-principles anti-pattern #4).  Higher quadrature
    order (LS6 → N=48) stresses the reduction-tree drift path the
    most among the LS family.  Spatially varying Q (rng-fixed
    gradient) ensures the redistribution term is ACTIVE — uniform Q +
    uniform Σ_t would null it.
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="vacuum", bc_xmax="vacuum",
        bc_ymin="vacuum", bc_ymax="vacuum",
        quadrature="LS6", n_materials=2, ng=2,
    )
    materials = {0: get_mixture("A", "2g"), 1: get_mixture("B", "2g")}
    sig_t = _build_sig_t(sn_mesh, materials, ng=2)
    rng = np.random.default_rng(seed=4)
    # Smoothly varying Q across both axes; group-asymmetric magnitudes
    # to catch any ng-axis swap.  PR-INDEX-4: build in legacy
    # (nx, ny, ng) then transpose to principled (ng, nx, ny) so the
    # numerical values are identical to pre-PR-INDEX-4 snapshots after
    # a single layout flip — bit-identity preserved by view-only
    # transpose.
    x = np.linspace(0.0, 1.0, sn_mesh.nx)[:, None, None]
    y = np.linspace(0.0, 1.0, sn_mesh.ny)[None, :, None]
    Q_legacy = (
        np.array([1.0, 0.5])[None, None, :]
        + 0.5 * x + 0.3 * y
        + 0.1 * rng.standard_normal((sn_mesh.nx, sn_mesh.ny, 2))
    )
    Q = np.transpose(Q_legacy, (2, 0, 1)).copy()  # (ng, nx, ny)
    return OctantEquivalenceInputs(
        sn_mesh=sn_mesh, Q=Q, sig_t=sig_t,
        boundary_flux=sn_mesh.zeros_boundary_flux(), aniso_source=None,
    )


# ─── case-5 — Q_aniso branch ─────────────────────────────────────────


def _case_5_q_aniso() -> OctantEquivalenceInputs:
    """Mixed BC, 2G asymmetric heterogeneous, gradient Q, Q_aniso != None.

    Failure mode coverage: AI failure mode #5 (Q_aniso branch).  The
    legacy sweep takes ``Q_aniso`` (per-ordinate anisotropic source)
    optionally; the new code must reproduce both the
    ``Q_aniso=None`` and ``Q_aniso != None`` paths.  This case
    constructs a non-trivial Q_aniso (rng-fixed Wave-1
    R∘Λ∘M-emulating per-ordinate field — but built directly without
    requiring the Wave-1 plumbing, so the case is self-contained).
    Run with ``n_sweeps=2`` so the second sweep stresses the
    L7-trap on the Q_aniso code path (reflective BC apply at each
    octant must read post-first-sweep buffer, not stale intra-sweep
    buffer).
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="reflective", bc_xmax="vacuum",
        bc_ymin="reflective", bc_ymax="vacuum",
        quadrature="LS4", n_materials=2, ng=2,
    )
    materials = {0: get_mixture("A", "2g"), 1: get_mixture("B", "2g")}
    sig_t = _build_sig_t(sn_mesh, materials, ng=2)
    rng = np.random.default_rng(seed=5)
    # PR-INDEX-4: build legacy then flip to principled (ng, nx, ny) /
    # (N, ng, nx, ny) for the numerical-value parity with pre-PR-4
    # snapshots.
    x = np.linspace(0.0, 1.0, sn_mesh.nx)[:, None, None]
    y = np.linspace(0.0, 1.0, sn_mesh.ny)[None, :, None]
    Q_legacy = (
        np.array([1.0, 0.5])[None, None, :]
        + 0.5 * x + 0.3 * y
    )
    Q = np.transpose(Q_legacy, (2, 0, 1)).copy()  # (ng, nx, ny)
    # Q_aniso legacy shape (N, nx, ny, ng) → principled (N, ng, nx, ny).
    N = sn_mesh.quad.N
    mu_x = sn_mesh.quad.mu_x[:, None, None, None]
    mu_y = sn_mesh.quad.mu_y[:, None, None, None]
    Q_aniso_legacy = (
        0.2 * mu_x * Q_legacy[None, ...] + 0.1 * mu_y * Q_legacy[None, ...]
        + 0.05 * rng.standard_normal((N, sn_mesh.nx, sn_mesh.ny, 2))
    )
    Q_aniso = np.transpose(Q_aniso_legacy, (0, 3, 1, 2)).copy()  # (N, ng, nx, ny)
    return OctantEquivalenceInputs(
        sn_mesh=sn_mesh, Q=Q, sig_t=sig_t,
        boundary_flux=_empty_boundary_flux(sn_mesh), aniso_source=Q_aniso,
    )


# ─── case-6 — pure-z degenerate ordinate (Lebedev order 5) ────────────


def _case_6_pure_z() -> OctantEquivalenceInputs:
    """Vacuum BC, 1G homogeneous, Lebedev order 5 (has two pure-z ordinates).

    Failure mode coverage: pure-z degenerate-ordinate skip path.
    Lebedev order 5 has two ordinates with ``|μ_x| < 1e-15 AND
    |μ_y| < 1e-15`` (n=4: ``(0,0,+1)``, n=5: ``(0,0,-1)``) which
    cannot stream in 2-D.  In the legacy code these take the
    ``psi_avg = Q_n / sig_t`` branch and skip the spatial sweep.  The
    new code must produce the same output via the
    ``sign_x == 0 == sign_y`` branch in its octant dispatch.

    No project quadrature in the Sn family (Sn order 4, 6) exhibits
    pure-z; Lebedev is the only family that does, so we use it here.
    Documenting the choice: this case is the ONLY harness row whose
    quadrature deliberately differs from the rest — the deviation is
    necessary to exercise the degenerate path.
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="vacuum", bc_xmax="vacuum",
        bc_ymin="vacuum", bc_ymax="vacuum",
        quadrature="Lebedev5", n_materials=1,
    )
    materials = {0: get_mixture("A", "1g")}
    sig_t = _build_sig_t(sn_mesh, materials, ng=1)
    Q = np.ones((1, sn_mesh.nx, sn_mesh.ny))  # PR-INDEX-4 (ng, nx, ny)
    return OctantEquivalenceInputs(
        sn_mesh=sn_mesh, Q=Q, sig_t=sig_t,
        boundary_flux=sn_mesh.zeros_boundary_flux(), aniso_source=None,
    )


# ─── case-7 — closed-form L1 anchor (φ = Q/Σ_t) ──────────────────────


@dataclass(frozen=True)
class _ClosedFormAnchorInputs:
    """Inputs for case 7's converged-solution closed-form anchor.

    Issue #196 PR-INDEX-5: principled ``(ng, nx, ny)`` storage.
    """

    sn_mesh: SNMesh
    Q: np.ndarray              # (ng, nx, ny)
    materials: dict
    expected_phi: np.ndarray   # (ng, nx, ny) — the analytical Q/Σ_t


def _case_7_closed_form_anchor() -> _ClosedFormAnchorInputs:
    r"""All-reflective + uniform Q + uniform Σ_t → φ = Q/Σ_t exactly.

    Closed-form L1 anchor, **structurally independent** of the legacy
    code.  Under all-reflective BCs the system is an infinite medium
    in disguise; for spatially uniform Σ_t and uniform isotropic
    external Q the steady-state transport equation reduces to the
    streaming-equilibrium identity

    .. math::

        \mu \cdot \nabla \psi + \Sigma_t \psi = \frac{Q}{4\pi}
        \implies \psi = \frac{Q}{4\pi \Sigma_t},
        \quad \phi = 4\pi \psi = \frac{Q}{\Sigma_t}.

    For the SN solver this is the canonical streaming-equilibrium
    diagnostic (also the catching test for AI failure mode #4 /
    Signature 4 / ERR-004 / ERR-025 — a wrong ``Σw`` normalisation
    produces a constant-factor drift from ``Q/Σ_t``).

    The single sweep does NOT converge to this in one shot
    (reflective-BC buffers must equilibrate); we therefore drive
    convergence via :func:`solve_sn_fixed_source` (the iteration that
    consumes ``_sweep_2d_wavefront`` repeatedly) and assert the
    converged scalar flux matches ``Q/Σ_t`` to ``rtol=1e-12,
    atol=1e-13``.  This makes case 7 an L1 verification (analytical
    reference, structurally independent of legacy) rather than a
    regression-snapshot inheritance like cases 1-6.

    Tolerance: ``rtol=1e-7, atol=1e-8``.  The reflective-BC
    convergence floor for ``solve_sn_fixed_source`` on this 3×3 mesh
    with ``inner_tol=1e-13`` and ``max_inner=500`` saturates at ~3e-9
    relative — the source iteration has slow tail decay on
    reflective-BC problems even with very tight inner tolerances
    because each iteration shaves a fixed fraction of the imbalance.
    ``rtol=1e-7`` (a ~30× margin over the observed ~3e-9 floor) gates
    against any algebraic drift while accepting the iteration-floor
    residual.  This is loose compared to the ``nulp=64`` bit-identity
    contract on cases 1-6, but it is the L1 anchor's role: prove the
    legacy code is correct on a structurally-independent reference,
    not gate against single-ULP drift.

    NOTE: 1G homogeneous would be degenerate (vv-principles
    Cardinal Rule 6).  We use 2G to avoid the degeneracy AND to
    confirm the anchor holds in the multi-group case.  The
    streaming-equilibrium identity is per-group, so the analytical
    reference for 2G is φ_g = Q_g / (Σ_t,g - Σ_s,g→g - Σ_s,g'→g·R)
    with R = Q_g'/Q_g for the steady scattering-coupled equilibrium.
    To keep the anchor algebraically clean we use a SCATTERING-FREE
    "C" mixture (strong absorber, no fission) where the per-group
    equation decouples and φ_g = Q_g / Σ_t,g exactly.
    """
    sn_mesh = _build_sn_mesh(
        nx=3, ny=3,
        bc_xmin="reflective", bc_xmax="reflective",
        bc_ymin="reflective", bc_ymax="reflective",
        quadrature="LS4", n_materials=1,
    )
    # "C" mixture = strong absorber, minimal scattering — closest
    # decoupling to a pure-absorber per-group identity in the
    # xs_library set.  We use 2G to comply with vv-principles Cardinal
    # Rule 6 (no 1G eigenvalue / equilibrium tests).  For "C" 2G the
    # scattering matrix is small but nonzero, so the analytical
    # reference uses the full per-group balance:
    #
    #   (Σ_t,g - Σ_s,g→g) φ_g = Q_g + Σ_{g' ≠ g} Σ_s,g'→g φ_{g'}
    #
    # which is a 2×2 linear system in (φ_0, φ_1) — closed-form,
    # structurally independent of the SN sweep.
    mix = get_mixture("C", "2g")
    materials = {0: mix}
    Q_per_group = np.array([1.0, 0.5])
    # Issue #196 PR-INDEX-5: principled (ng, nx, ny).
    Q = np.broadcast_to(
        Q_per_group[:, None, None], (2, sn_mesh.nx, sn_mesh.ny),
    ).copy()
    # Build the (Σ_t,g - Σ_s,g→g)·δ_{gg'} - Σ_s,g'→g (off-diag) matrix.
    # ``mix.sig_s[0]`` is the P0 scattering matrix with ``[g_src, g_dst]``
    # convention (xs_library docstring).  The transport balance reads:
    #     Σ_t,g φ_g = Q_g + Σ_{g_src} Σ_s[g_src, g] φ_{g_src}
    # i.e.   (Σ_t δ_{gg'} - Σ_s^T) φ = Q.
    sig_t_vec = mix.SigT                        # (2,)
    sig_s = mix.SigS[0]                         # (2, 2), [g_src, g_dst]
    A = np.diag(sig_t_vec) - sig_s.T            # apply transpose for [g_dst, g_src]
    phi_per_group = np.linalg.solve(A, Q_per_group)
    # Issue #196 PR-INDEX-5: principled (ng, nx, ny).
    expected_phi = np.broadcast_to(
        phi_per_group[:, None, None], (2, sn_mesh.nx, sn_mesh.ny),
    ).copy()
    return _ClosedFormAnchorInputs(
        sn_mesh=sn_mesh, Q=Q, materials=materials,
        expected_phi=expected_phi,
    )


# Registry — the seven cases.
CASES: tuple[OctantEquivalenceCase, ...] = (
    OctantEquivalenceCase(
        case_id="01_smoke_vacuum_1g_homog_uniformQ_LS4",
        description=(
            "All-vacuum, 1G, homogeneous A mixture, uniform Q, LS_4. "
            "Smoke test for per-octant anti-diagonal coverage."
        ),
        failure_mode="#2 anti-diagonal coverage",
        builder=_case_1_smoke,
    ),
    OctantEquivalenceCase(
        case_id="02_reflective_1g_homog_uniformQ_LS4",
        description=(
            "All-reflective, 1G, homogeneous A mixture, uniform Q, LS_4, "
            "two consecutive sweeps. Reflective-BC equivalence."
        ),
        failure_mode="#1 BC ordering on reflective",
        builder=_case_2_reflective,
        n_sweeps=2,
    ),
    OctantEquivalenceCase(
        case_id="03_l7_trap_mixedBC_2g_het_LS4",
        description=(
            "L7-TRAP — mixed BC (refl L+B, vac R+T), 2G A|B het, "
            "uniform Q, LS_4, two consecutive sweeps."
        ),
        failure_mode="#1 L7-trap + #4 multi-group het + ERR-003",
        builder=_case_3_l7_trap,
        n_sweeps=2,
    ),
    OctantEquivalenceCase(
        case_id="04_vacuum_2g_het_gradientQ_LS6",
        description=(
            "All-vacuum, 2G A|B heterogeneous, gradient Q, LS_6. "
            "Multi-group + heterogeneous (L2)."
        ),
        failure_mode="#4 multi-group het + reduction drift (LS6 N=48)",
        builder=_case_4_heterogeneous,
    ),
    OctantEquivalenceCase(
        case_id="05_qaniso_mixedBC_2g_het_LS4",
        description=(
            "Q_aniso branch — mixed BC, 2G A|B het, gradient Q, "
            "non-trivial Q_aniso, LS_4, two consecutive sweeps."
        ),
        failure_mode="#5 Q_aniso branch + L7-trap on aniso path",
        builder=_case_5_q_aniso,
        n_sweeps=2,
    ),
    OctantEquivalenceCase(
        case_id="06_purez_vacuum_1g_Lebedev5",
        description=(
            "Pure-z degenerate ordinates — Lebedev order 5 (N=14, "
            "two pure-z), all-vacuum, 1G homogeneous, uniform Q."
        ),
        failure_mode="#3 pure-z skip path (sign_x==0==sign_y)",
        builder=_case_6_pure_z,
    ),
)


def _snapshot_path(case_id: str) -> Path:
    return SNAPSHOT_DIR / f"2d_octant_equivalence_{case_id}.npz"


# ═══════════════════════════════════════════════════════════════════
# Cases 1-6 — bit-identity (within nulp) against the snapshots
# ═══════════════════════════════════════════════════════════════════


@pytest.mark.regression
@pytest.mark.catches("ERR-003")
@pytest.mark.parametrize("case", CASES, ids=lambda c: c.case_id)
def test_2d_octant_sweep_equivalence(case: OctantEquivalenceCase) -> None:
    """Re-run the case and assert bit-identity (within nulp) vs snapshot.

    Snapshots are generated by
    ``python -m tests.sn.regression._generate_2d_octant_snapshots`` on
    the LEGACY commit (BEFORE the Wave-2 refactor).  After the refactor
    lands, the new sweep must reproduce the same outputs to within
    ``nulp=64`` (worst-case ``N × ULP`` reduction-tree drift; see
    file docstring for the budget derivation).

    What this test gates against:

    * A wrong reduction order in the new code that would exceed the
      ``N × ULP`` drift budget.
    * Any algorithmic divergence between legacy and refactored code:
      missing-cell coverage, wrong topological order, BC apply
      misordering, Q_aniso path drift, pure-z dispatch divergence.

    What this test does NOT gate against:

    * The legacy code's correctness in the absolute — that's case 7.
      This test inherits from the legacy snapshots; if the legacy was
      wrong, this gates against drift from a wrong baseline.  Case 7
      provides the structurally-independent grounding.
    """
    snapshot_file = _snapshot_path(case.case_id)
    if not snapshot_file.exists():
        pytest.skip(
            f"snapshot {snapshot_file.name} not yet generated; run "
            "`python -m tests.sn.regression._generate_2d_octant_snapshots`",
        )

    inputs = case.builder()

    # Run the (current) sweep ``n_sweeps`` times, sharing psi_bc.
    # The snapshot captures the FINAL sweep's outputs and the
    # FINAL post-sweep psi_bc state.  The L7-trap surfaces in the
    # second-sweep outputs because only on the second sweep does the
    # reflective-BC apply READ buffer content written by an earlier
    # sweep — single-sweep cases would hide the trap (the buffer is
    # all-zero or seeded but immediately overwritten before any read).
    angular_flux = scalar_flux = None
    for _ in range(case.n_sweeps):
        angular_flux, scalar_flux = _sweep_2d_wavefront(
            inputs.Q, inputs.sig_t, inputs.sn_mesh, inputs.boundary_flux,
            Q_aniso=inputs.aniso_source,
        )

    snap = np.load(snapshot_file)
    # Issue #196 PR-INDEX-5: snapshots are stored in principled layout
    # (``angular_flux: (N, ng, nx, ny)`` etc.) — same as the sweep's
    # native output.  No transpose required.
    expected_angular = np.asarray(snap["angular_flux"], dtype=np.float64)
    expected_scalar = np.asarray(snap["scalar_flux"], dtype=np.float64)
    expected_psi_x = np.asarray(snap["psi_x_post"], dtype=np.float64)
    expected_psi_y = np.asarray(snap["psi_y_post"], dtype=np.float64)

    # Bit-identity contract — angular flux, scalar flux, AND post-sweep
    # BC buffers.  All three are MUST-MATCH because (i) angular flux is
    # the primary output, (ii) scalar flux carries the
    # einsum-reduction order that drifts most in the refactor,
    # (iii) post-sweep BC buffers are the stateful link between
    # consecutive source iterations — drift here would silently
    # contaminate downstream iterations.
    np.testing.assert_array_almost_equal_nulp(
        np.asarray(angular_flux, dtype=np.float64),
        expected_angular, nulp=case.nulp,
    )
    np.testing.assert_array_almost_equal_nulp(
        np.asarray(scalar_flux, dtype=np.float64),
        expected_scalar, nulp=case.nulp,
    )
    np.testing.assert_array_almost_equal_nulp(
        np.asarray(inputs.boundary_flux.xmin_xmax_buf, dtype=np.float64),
        expected_psi_x, nulp=case.nulp,
    )
    np.testing.assert_array_almost_equal_nulp(
        np.asarray(inputs.boundary_flux.ymin_ymax_buf, dtype=np.float64),
        expected_psi_y, nulp=case.nulp,
    )


# ═══════════════════════════════════════════════════════════════════
# Case 7 — L1 closed-form anchor (φ = Q/Σ_t under reflective+uniform)
# ═══════════════════════════════════════════════════════════════════


@pytest.mark.verifies("transport-cartesian-2d", "dd-cartesian-2d", "multigroup")
def test_2d_octant_sweep_closed_form_anchor() -> None:
    r"""L1 anchor: all-reflective + uniform Q + uniform Σ_t → φ_g = (A^{-1} Q)_g.

    Structurally-independent reference (analytical).  The reference is
    NOT a snapshot from the legacy code — it is the exact streaming-
    equilibrium identity solved in closed form via numpy.linalg.solve
    on the 2×2 multi-group balance matrix.  This is what makes case 7
    L1 (analytical reference) rather than L1+regression (cases 1-6).

    Tolerance: ``rtol=1e-7, atol=1e-8`` — see the
    :func:`_case_7_closed_form_anchor` docstring for the budget
    derivation (reflective-BC iteration-floor saturation).

    Why this case is needed even though cases 1-6 are bit-identity:
    cases 1-6 prove the new code agrees with the legacy code; they
    cannot prove either was correct in the first place.  Case 7
    proves the legacy code is correct on at least one verified
    configuration, which (combined with the bit-identity gate)
    transitively grounds the new code.
    """
    inputs = _case_7_closed_form_anchor()

    result = solve_sn_fixed_source(
        inputs.materials, inputs.sn_mesh.mesh, inputs.sn_mesh.quad,
        # solve_sn_fixed_source expects external_source shape
        # ``(N, ng, nx, ny)`` (Issue #196 PR-INDEX-5 — principled).
        # Replicate the isotropic Q across ordinates without any
        # per-ordinate dependence.
        external_source=np.broadcast_to(
            inputs.Q[None, ...],
            (inputs.sn_mesh.quad.N, *inputs.Q.shape),
        ).copy(),
        scattering_order=0,
        boundary_condition="reflective",
        max_inner=500, inner_tol=1e-13,
    )

    np.testing.assert_allclose(
        np.asarray(result.scalar_flux.values, dtype=np.float64),
        inputs.expected_phi,
        rtol=1e-7, atol=1e-8,
        err_msg=(
            "All-reflective + uniform Q + uniform Σ_t (multi-group "
            "balance) closed-form anchor failed: φ does NOT match "
            "(diag(Σ_t) - Σ_s^T)^{-1} Q.  "
            f"max |diff| = {np.max(np.abs(np.asarray(result.scalar_flux.values) - inputs.expected_phi)):.3e}"
        ),
    )
