"""One red per arm of the two write guards in ``.claude/hooks/`` (instrument-doctrine X1): the
project-wide ``generated-guard`` (a hand edit of generated text, or of an installed file) and the
per-agent ``write-scope`` (a write outside scratch, the temporary directory and the agent's own
memory). Each hook runs as the harness runs it: a subprocess reading the PreToolUse payload on stdin,
exit 2 to refuse.
"""
from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys

import pytest

pytestmark = pytest.mark.foundation

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
GUARD = REPO_ROOT / ".claude" / "hooks" / "generated-guard.py"
SCOPE = REPO_ROOT / ".claude" / "hooks" / "write-scope.py"

STAMPED = "<!-- GENERATED by tools/harness from docs/development/rules/r.md — DO NOT EDIT. -->\n# R\n\nrule text\n"
BLOCKED = ("---\nname: a\nmodel: opus\n---\n\n"
           "<!-- BEGIN GENERATED definition — source: docs/development/agents/a.md; edit the source, not this block -->\n"
           "# a\n\nthe method\n<!-- END GENERATED definition -->\n")


def run(hook: pathlib.Path, payload: dict, cwd: pathlib.Path, *args: str) -> tuple[int, str]:
    env = {k: v for k, v in os.environ.items() if k != "CLAUDE_PROJECT_DIR"}
    done = subprocess.run([sys.executable, str(hook), *args], input=json.dumps({**payload, "cwd": str(cwd)}),
                          capture_output=True, text=True, env=env, check=False)
    return done.returncode, done.stderr


def write(path: pathlib.Path, text: str) -> pathlib.Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def edit(path: pathlib.Path, old: str, new: str = "x") -> dict:
    return {"tool_name": "Edit", "tool_input": {"file_path": str(path), "old_string": old, "new_string": new}}


# ------------------------------------------------------------ generated-guard

def test_a_stamped_file_refuses_every_edit_and_names_its_source(tmp_path: pathlib.Path) -> None:
    f = write(tmp_path / "rules" / "r.md", STAMPED)
    code, why = run(GUARD, edit(f, "rule text"), tmp_path)
    assert code == 2 and "docs/development/rules/r.md" in why and "tools.harness" in why
    assert run(GUARD, {"tool_name": "Write", "tool_input": {"file_path": str(f), "content": "new"}}, tmp_path)[0] == 2


def test_a_block_refuses_an_edit_inside_it_and_passes_one_outside(tmp_path: pathlib.Path) -> None:
    f = write(tmp_path / "AGENT.md", BLOCKED)
    code, why = run(GUARD, edit(f, "the method"), tmp_path)
    assert code == 2 and "definition" in why and "docs/development/agents/a.md" in why
    assert run(GUARD, edit(f, "model: opus", "model: sonnet"), tmp_path)[0] == 0, "the front matter is hand-maintained"
    multi = {"tool_name": "MultiEdit", "tool_input": {"file_path": str(f), "edits": [
        {"old_string": "model: opus", "new_string": "model: sonnet"}, {"old_string": "# a", "new_string": "# b"}]}}
    assert run(GUARD, multi, tmp_path)[0] == 2, "one edit of a MultiEdit inside the block refuses the call"


def test_a_write_passes_when_the_block_is_unchanged_and_refuses_when_it_changes(tmp_path: pathlib.Path) -> None:
    f = write(tmp_path / "AGENT.md", BLOCKED)
    same = {"tool_name": "Write", "tool_input": {"file_path": str(f), "content": BLOCKED.replace("opus", "sonnet")}}
    changed = {"tool_name": "Write", "tool_input": {"file_path": str(f), "content": BLOCKED.replace("the method", "a hand edit")}}
    assert run(GUARD, same, tmp_path)[0] == 0
    assert run(GUARD, changed, tmp_path)[0] == 2


def test_an_installed_file_is_refused(tmp_path: pathlib.Path) -> None:
    write(tmp_path / ".claude" / "nexus-install-manifest.json", json.dumps({"files": {"rules/nexus-tools.md": {"version": "1"}}}))
    f = write(tmp_path / ".claude" / "rules" / "nexus-tools.md", "# routing\n")
    code, why = run(GUARD, edit(f, "routing"), tmp_path)
    assert code == 2 and "nexus" in why


@pytest.mark.parametrize("payload", [
    lambda p: edit(p / "plain.md", "hand text"),
    lambda p: {"tool_name": "Write", "tool_input": {"file_path": str(p / "new.md"), "content": "x"}},
    lambda p: {"tool_name": "Bash", "tool_input": {"command": "echo x > plain.md"}},
])
def test_a_hand_maintained_file_a_new_file_and_another_tool_pass(tmp_path: pathlib.Path, payload) -> None:
    write(tmp_path / "plain.md", "hand text\n")
    assert run(GUARD, payload(tmp_path), tmp_path)[0] == 0


def test_the_real_tree_is_guarded_where_it_is_generated_and_open_where_it_is_not() -> None:
    """Positive controls on the files the guard exists for."""
    rule = REPO_ROOT / ".claude" / "rules" / "cardinal.md"
    qa = REPO_ROOT / ".claude" / "agents" / "qa" / "AGENT.md"
    assert run(GUARD, edit(rule, "Correctness"), REPO_ROOT)[0] == 2
    assert run(GUARD, edit(qa, "model: opus", "model: opus"), REPO_ROOT)[0] == 0
    # the definition's own H1, which every rewrite keeps: an anchor on a section heading went stale once
    heading = "\n# qa\n"
    assert heading in qa.read_text(encoding="utf-8"), "the control's anchor is gone from the generated block"
    assert run(GUARD, edit(qa, heading, "\n# qa (probe)\n"), REPO_ROOT)[0] == 2
    assert run(GUARD, edit(REPO_ROOT / ".claude" / "rules" / "nexus-tools.md", "Nexus"), REPO_ROOT)[0] == 2
    assert run(GUARD, edit(REPO_ROOT / "docs" / "development" / "agents" / "qa.md", heading), REPO_ROOT)[0] == 0


# ---------------------------------------------------------------- write-scope

@pytest.mark.parametrize("rel, expected", [
    ("scratch/_x/report.md", 0),
    (".claude/agent-memory/qa/lessons.md", 0),
    (".claude/agent-memory/archivist/lessons.md", 2),
    ("orpheus/sn/solver.py", 2),
    ("docs/theory/index.rst", 2),
])
def test_write_scope_allows_scratch_and_own_memory_only(rel: str, expected: int) -> None:
    # the project is the real root, outside the temporary directory; the hook reads paths and writes nothing
    code, why = run(SCOPE, edit(REPO_ROOT / rel, "a"), REPO_ROOT, "qa")
    assert code == expected, why
    if expected:
        assert "qa writes only under scratch/" in why and "SendMessage" in why


def test_write_scope_allows_the_temporary_directory_and_resolves_a_relative_path() -> None:
    import tempfile
    assert run(SCOPE, edit(pathlib.Path(tempfile.gettempdir()) / "probe.py", "a"), REPO_ROOT, "qa")[0] == 0
    relative = {"tool_name": "Write", "tool_input": {"file_path": "orpheus/x.py", "content": "x"}}
    assert run(SCOPE, relative, REPO_ROOT, "qa")[0] == 2
    relative_ok = {"tool_name": "Write", "tool_input": {"file_path": "scratch/x.md", "content": "x"}}
    assert run(SCOPE, relative_ok, REPO_ROOT, "qa")[0] == 0


def test_write_scope_passes_other_tools() -> None:
    assert run(SCOPE, {"tool_name": "Bash", "tool_input": {"command": "ls"}}, REPO_ROOT, "qa")[0] == 0
