r"""L0 streaming-equilibrium test for curvilinear SN — sphere + cylinder.

Issue #196 Phase G Step 2 Path C (2026-05-13).  Promoted from the
diagnostic probe ``tests/sn/diagnostics/phase_g_step2_05_homogeneous.py``
to the V&V-tagged regression tier.

Test premise
------------

Homogeneous reflective sphere (or cylinder) with isotropic external
source ``Q`` and subcritical mixture (``c = (Σ_s + νΣ_f)/Σ_t < 1``)
admits a closed-form analytical solution:

* Scalar flux: :math:`\varphi(r) = Q / (\Sigma_t (1 - c))` — uniform.
* Per-ordinate angular flux: :math:`\psi_n(r) = \varphi / \Sigma w` —
  the Pomraning 1989 (NSE 102:317-336) structural-singularity result
  that ψ MUST be isotropic at the pole/axis (where the curvilinear
  redistribution operator becomes singular), combined with reflective-
  BC symmetry that propagates the pole isotropy to all r.

For mixture B 1G (Σ_t = 2, Σ_s = 1.9 so c = 0.95) with Q = 1:
``φ_analytic = 10``, ``ψ_n = 10/Σw = 5`` for every ordinate at every cell.

Why this test catches ERR-048 (and not the prior pole tests)
------------------------------------------------------------

The two algebraic defects fixed in Phase G Step 2 (pole-face WDD IC,
Carlson seed source) are convention disagreements between
``_sweep_1d_spherical`` / ``_sweep_1d_cylindrical`` (SI path) and
``transport_operator_matvec_spherical`` / ``_cylindrical`` (apply-
matvec path).  Both production paths converge to *their own* fixed
points to machine precision — neither path is "diverging."  The
defects are invisible to:

* SI residual norm (it converges; the residual is on the wrong
  operator).
* Krylov-vs-SI keff agreement (both fixed-source converged-keff are
  close on simple problems; the discrepancy is in the flux shape).
* Existing Phase F regression snapshots (they were generated by the
  buggy SI sweep — bit-identity preserves the wrong answer).

The streaming-equilibrium analytical answer ``ψ_n = Q/(Σ_t·Σw·(1-c))``
is structurally independent of both production paths (it is a closed-
form scalar from the homogeneous reflective infinite-medium balance,
not derived from any discretisation).  This test compares each
production path against the analytical truth and tagged as L0 —
the canonical streaming-equilibrium gate per
:doc:`/theory/methods/sn/curvilinear_one_group`.

References
----------

* Lewis-Miller §4.5 — Carlson starting-direction convention.
* Hébert §3.9.4 Eqs. (3.432)-(3.435) — Carlson coupled-pole seed.
* Pomraning 1989 NSE 102:317-336 — structural-singularity isotropy
  at the pole/axis.
"""
from __future__ import annotations

import numpy as np
import pytest

from orpheus.derivations.common.xs_library import get_mixture
from orpheus.geometry import BC, Mesh1D, Region, RegionMesh, StructuredGeometry
from orpheus.numerics.quadrature import Quadrature
from orpheus.sn.solver import solve_sn_fixed_source


# ── Analytical reference ───────────────────────────────────────────
# Mixture B 1G: SigT = 2, SigS_self = 1.9, no fission.  c = 0.95.
# φ_analytic = Q / (Σ_t - Σ_s) = 1 / 0.1 = 10.
# ψ_analytic = φ_analytic / Σw  (Pomraning isotropy + reflective BC).

_R_SPHERE = 2.0   # cm
_R_CYL = 2.0      # cm


def _expected_psi(quad) -> float:
    return 1.0 / 0.1 / quad.weights.sum()


def _expected_phi() -> float:
    return 1.0 / 0.1  # = 10.0


# ── Sphere tests ───────────────────────────────────────────────────

@pytest.mark.l0
@pytest.mark.verifies("hebert-3-432")
@pytest.mark.catches("ERR-026", "ERR-048")
@pytest.mark.parametrize("n_cells", [20, 40, 80])
@pytest.mark.parametrize("n_ord", [8, 16])
@pytest.mark.parametrize("inner_solver", ["source_iteration", "krylov"])
def test_homogeneous_streaming_equilibrium_sphere(
    n_cells: int, n_ord: int, inner_solver: str,
) -> None:
    r"""Homogeneous reflective sphere → analytical streaming equilibrium.

    Both ``source_iteration`` and ``krylov`` inner solvers must reach
    the closed-form analytical answer ``φ = Q/(Σ_t(1-c))`` and
    per-ordinate ``ψ_n = φ/Σw`` to ``rtol = 1e-9`` at every cell, for
    every ordinate, across the parameter grid.

    Catches ERR-048 (Phase G Step 2 Path C): pre-fix the
    ``source_iteration`` path converged to a contaminated fixed point
    with ~15-22% per-cell error on this gauntlet; the apply-matvec
    Krylov path was correct.

    Inherits the ERR-026 catch tag from the retired
    ``tests/sn/test_sweep_operator_inconsistency.py`` evidence ledger
    (PR-CLEANUP-CODE §C).  ERR-026 — the curvilinear sweep WDD wrong
    fixed-point bug — manifested as a non-flat ψ from constant-source
    reflective-BC inputs; THIS test is the canonical post-closure
    evidence that the SI path now reaches the correct streaming-
    equilibrium fixed point (φ = Q/(Σ_t(1-c)), ψ_n = φ/Σw) under both
    inner solvers, on the canonical L0 gauntlet.
    """
    fuel = get_mixture("B", "1g")
    geom = StructuredGeometry(
        geometry="SPH",
        regions=(Region(mat_id=0, outer_thickness_cm=_R_SPHERE),),
        bcs=(BC.reflective,),
    )
    mesh = Mesh1D.from_geometry(
        geom, region_meshes=(RegionMesh(n_cells=n_cells),),
    )
    quad = Quadrature.gauss_legendre(n_ordinates=n_ord)
    N = quad.N
    nx = mesh.N
    ng = 1
    # R-1 Step 4 A1 — ``external_source`` is per-ordinate density
    # (already projected via ``/sum_w``).  Iso scalar magnitude 1 ⇒
    # per-ord density ``1/sum_w``.
    sum_w = float(np.sum(quad.weights))
    Q = np.full((N, ng, nx), 1.0 / sum_w)

    result = solve_sn_fixed_source(
        materials={0: fuel}, mesh=mesh, quadrature=quad, external_source=Q,
        boundary_condition="reflective", inner_solver=inner_solver,
    )
    # D-H.1d: Solution.angular_flux is TimedFullField.
    psi = result.angular_flux.interior.values   # (N, ng, nx)
    sf = result.scalar_flux.values          # (ng, nx)

    psi_expected = _expected_psi(quad)
    phi_expected = _expected_phi()

    np.testing.assert_allclose(
        psi, psi_expected, rtol=1e-9,
        err_msg=(
            f"Per-ordinate ψ deviates from Pomraning isotropy "
            f"(expected {psi_expected:.6f} = {phi_expected}/Σw).  "
            f"Configuration: sphere, n_cells={n_cells}, n_ord={n_ord}, "
            f"inner_solver={inner_solver}.  ERR-048 is open if this "
            f"fails on source_iteration but passes on krylov."
        ),
    )
    np.testing.assert_allclose(
        sf, phi_expected, rtol=1e-9,
        err_msg=(
            f"Scalar flux deviates from streaming-equilibrium analytical "
            f"limit φ = Q/(Σ_t(1-c)) = {phi_expected}.  Configuration: "
            f"sphere, n_cells={n_cells}, n_ord={n_ord}, "
            f"inner_solver={inner_solver}."
        ),
    )


# ── Sentinel (canary) — cheapest single curvilinear-pole probe ──────
# One sentinel for the ``sweep_curvilinear`` capability node: the
# cheapest config of the gauntlet above (n_cells=20, n_ord=8, SI).
# Sharp at the r=0 pole corner + the WDD curvilinear fixed point.
# Delegates to the same solver path so it tracks the matrix test.
# See .claude/plans/archive/sn_sentinel_harness.md.


@pytest.mark.sentinel
@pytest.mark.l0
@pytest.mark.verifies("hebert-3-432")
@pytest.mark.catches("ERR-026", "ERR-048")
def test_sentinel_sphere_streaming_equilibrium() -> None:
    r"""Sentinel: sphere streaming-equilibrium at the cheapest config.

    Canary for the ``sweep_curvilinear`` capability node — a flip here
    localizes (via cap("sweep_curvilinear") + the DAG) to the
    angular-closure / Carlson-seed / WDD-curvilinear cluster.
    Same assertion as
    :func:`test_homogeneous_streaming_equilibrium_sphere` at
    ``n_cells=20, n_ord=8, inner_solver="source_iteration"``.
    """
    test_homogeneous_streaming_equilibrium_sphere(
        n_cells=20, n_ord=8, inner_solver="source_iteration",
    )


# ── Cylindrical tests ──────────────────────────────────────────────


@pytest.mark.l0
@pytest.mark.verifies("hebert-3-432")
@pytest.mark.catches("ERR-048")
@pytest.mark.parametrize("n_cells", [20, 40, 80])
@pytest.mark.parametrize("n_mu", [4, 8])
@pytest.mark.parametrize("inner_solver", ["source_iteration", "krylov"])
def test_homogeneous_streaming_equilibrium_cylinder(
    n_cells: int, n_mu: int, inner_solver: str,
) -> None:
    r"""Homogeneous reflective cylinder → analytical streaming equilibrium.

    Cylindrical analog of the spherical test above.  Uses the folded
    product quadrature (GL polar levels × the σ_y-quotiented staggered
    azimuthal arc) — the carrying family SNMesh(CYLINDRICAL) admits,
    with the M-M per-level azimuthal redistribution sweep marching the
    ψ½ system directly (Q5.6.3).

    Both inner solvers must converge to ψ_n = φ/Σw at every cell.
    Coverage: n_mu ∈ {4, 8} polar × parent n_phi = 4 azimuth (8 / 16
    folded ordinates) × 3 mesh sizes × 2 inner solvers = 12 cases.
    Larger ordinate counts add minutes per Krylov solve and provide no
    additional information against the analytical limit.
    """
    fuel = get_mixture("B", "1g")
    geom = StructuredGeometry(
        geometry="CYL",
        regions=(Region(mat_id=0, outer_thickness_cm=_R_CYL),),
        bcs=(BC.reflective,),
    )
    mesh = Mesh1D.from_geometry(
        geom, region_meshes=(RegionMesh(n_cells=n_cells),),
    )
    quad = Quadrature.folded_product(n_mu=n_mu, n_phi=4)
    N = quad.N
    nx = mesh.N
    ng = 1
    # R-1 Step 4 A1 — per-ordinate density (1 / sum_w).
    sum_w = float(np.sum(quad.weights))
    Q = np.full((N, ng, nx), 1.0 / sum_w)

    result = solve_sn_fixed_source(
        materials={0: fuel}, mesh=mesh, quadrature=quad, external_source=Q,
        boundary_condition="reflective", inner_solver=inner_solver,
    )
    # D-H.1d: Solution.angular_flux is TimedFullField.
    psi = result.angular_flux.interior.values   # (N, ng, nx)
    sf = result.scalar_flux.values          # (ng, nx)

    psi_expected = _expected_psi(quad)
    phi_expected = _expected_phi()

    np.testing.assert_allclose(
        psi, psi_expected, rtol=1e-9,
        err_msg=(
            f"Per-ordinate ψ deviates from Pomraning isotropy "
            f"(expected {psi_expected:.6f} = {phi_expected}/Σw).  "
            f"Configuration: cylinder, n_cells={n_cells}, n_mu={n_mu}, "
            f"inner_solver={inner_solver}."
        ),
    )
    np.testing.assert_allclose(
        sf, phi_expected, rtol=1e-9,
        err_msg=(
            f"Scalar flux deviates from streaming-equilibrium analytical "
            f"limit φ = {phi_expected}.  Configuration: cylinder, "
            f"n_cells={n_cells}, n_mu={n_mu}, "
            f"inner_solver={inner_solver}."
        ),
    )


# ── Pomraning per-ordinate isotropy at the pole ────────────────────


@pytest.mark.l0
@pytest.mark.verifies("hebert-3-432")
@pytest.mark.catches("ERR-048")
@pytest.mark.parametrize("inner_solver", ["source_iteration", "krylov"])
def test_pomraning_pole_isotropy_sphere(inner_solver: str) -> None:
    r"""Per-ordinate cv at the pole must be ≤ 0.01 on flat-flux input.

    Pomraning 1989 NSE 102:317-336: at the spherical pole r = 0 the
    angular flux must be isotropic because the curvilinear angular
    redistribution operator is singular there.  On a homogeneous
    reflective sphere with isotropic source, this isotropy propagates
    to all r via symmetry — ψ_n(r) = φ(r)/Σw, independent of n.

    A pre-Phase-G-Step-2 buggy SI sweep had cv(ψ@i=0) ≈ 0.52 on
    mixture B; this gate pins cv ≤ 0.01.
    """
    fuel = get_mixture("B", "1g")
    geom = StructuredGeometry(
        geometry="SPH",
        regions=(Region(mat_id=0, outer_thickness_cm=_R_SPHERE),),
        bcs=(BC.reflective,),
    )
    mesh = Mesh1D.from_geometry(geom, region_meshes=(RegionMesh(n_cells=40),))
    quad = Quadrature.gauss_legendre(n_ordinates=8)
    N = quad.N
    nx = mesh.N
    ng = 1
    # R-1 Step 4 A1 — per-ordinate density (1 / sum_w).
    sum_w = float(np.sum(quad.weights))
    Q = np.full((N, ng, nx), 1.0 / sum_w)

    result = solve_sn_fixed_source(
        materials={0: fuel}, mesh=mesh, quadrature=quad, external_source=Q,
        boundary_condition="reflective", inner_solver=inner_solver,
    )
    # D-H.1d: Solution.angular_flux is TimedFullField.
    psi_at_pole = result.angular_flux.interior.values[:, 0, 0]   # (N,)
    cv = float(np.std(psi_at_pole) / np.mean(psi_at_pole))
    assert cv < 0.01, (
        f"Pomraning pole isotropy violated for {inner_solver}: "
        f"cv(ψ@i=0) = {cv:.4e}, max = {psi_at_pole.max():.6f}, "
        f"min = {psi_at_pole.min():.6f}.  Pre-Phase-G-Step-2 SI "
        f"showed cv ≈ 0.52; the gate is 0.01."
    )
