r"""Quadrature on the circle :math:`S^1` — the periodic trapezoid.

The rule
========

:math:`n` equally-spaced points, all carrying weight :math:`2\pi/n`:

.. math::
   :label: periodic-trapezoid

   \int_{S^1} f \, d\varphi \;\approx\;
   \frac{2\pi}{n} \sum_{m=0}^{n-1} f(\varphi_m),
   \qquad
   \varphi_m = \frac{2\pi\,(m + s)}{n},

with :math:`s \in [0, 1)` a **shift measured in steps**. This is the
trapezoidal rule on a periodic function, where the two endpoint
half-weights merge into one full weight because the endpoints are the
same point — the "trapezoid" name survives from the interval, but on a
circle there is no endpoint to halve.

Why it is a separate module from :mod:`.rules_1d`
=================================================

**A rule on the circle and a rule on an interval are different objects
even when their nodes coincide**, and this rule exists to make that
distinction structural rather than a matter of the caller's intent.
`[M]` At :math:`s = \tfrac{1}{2}` these nodes are numerically the
midpoints that :func:`~orpheus.numerics.measure.equispaced` produces on
:math:`[0, 2\pi]` — yet the two carry incomparable claims:

.. list-table::
   :header-rows: 1
   :widths: 30 35 35

   * -
     - ``equispaced(0, 2π, n)``
     - ``periodic_trapezoid(n, shift=½)``
   * - space
     - the interval :math:`[0, 2\pi]`
     - the circle :math:`S^1`
   * - orthogonal system
     - polynomials
     - the Fourier basis
   * - degree
     - :math:`1`, always
     - :math:`n - 1`
   * - at :math:`n = 8`
     - exact on :math:`\{1, x\}`
     - exact on :math:`\{e^{ik\varphi}\}_{|k| \le 7}`

Reading the second as the first is the failure that made a naive
:math:`\min()` over the two rules' bare integers report degree **1** for
the sphere product rule whose true degree is
:math:`\min(2n_\mu - 1,\, n_\varphi - 1)` — the measured bug in
:mod:`orpheus.numerics.exactness`'s header.

The exactness theorem, and why it is tight
==========================================

Against the Fourier basis the rule's error is pure **aliasing**. For
:math:`f = e^{ik\varphi}`,

.. math::
   :label: periodic-trapezoid-aliasing

   \frac{2\pi}{n}\sum_{m=0}^{n-1} e^{ik\varphi_m}
   \;=\; \frac{2\pi}{n}\, e^{2\pi i k s/n}
         \sum_{m=0}^{n-1} \big(e^{2\pi i k/n}\big)^{m}
   \;=\; 2\pi\, e^{2\pi i k s/n}\,
         \big[\, k \equiv 0 \ (\mathrm{mod}\ n) \,\big],

because the inner geometric sum is :math:`n` when :math:`n \mid k` and
:math:`0` otherwise. The exact integral is :math:`2\pi\,[k = 0]`. The
two agree for every :math:`|k| \le n - 1` — the only multiple of
:math:`n` in that range is :math:`0` — and disagree at :math:`k = \pm n`
by the full :math:`2\pi`. So

.. math::

   \deg = n - 1, \qquad\text{and the bound is attained, not estimated.}

Two consequences that this module's tests pin, because both are
load-bearing downstream:

**The shift is exactness-invisible.** :math:`s` appears in
:eq:`periodic-trapezoid-aliasing` only through the phase
:math:`e^{2\pi i k s/n}`, which multiplies a factor that is already zero
for every :math:`k` the claim covers. No choice of shift can strengthen
or weaken the degree.

**The shift is nonetheless decisive.** Exactness-invisible is not the
same as irrelevant. What the shift decides is *where the nodes sit
relative to the mirror axes* — and hence whether the singular set
:math:`\Sigma = \{\xi = 0\}` of a fold through that mirror is empty.
Writing :math:`\sigma` for the reflection :math:`\varphi \to -\varphi`,
the node set is :math:`\sigma`-invariant iff
:math:`-\varphi_0 \equiv \varphi_0 \pmod{2\pi/n}`, i.e. iff
:math:`2s \in \mathbb{Z}` — so within the fundamental domain
:math:`s \in [0,1)` there are **exactly two** mirror-symmetric periodic
trapezoids:

* :math:`s = 0` — *node-aligned*: a node sits **on** the mirror axis, so
  :math:`\Sigma \neq \emptyset`;
* :math:`s = \tfrac{1}{2}` — *staggered*: the nodes straddle the axis in
  :math:`\sigma`-pairs, so :math:`\Sigma = \emptyset` for even
  :math:`n` (for odd :math:`n` the node at :math:`m = (n-1)/2` lands on
  :math:`\varphi = \pi`, the axis's other fixed point).

Every other shift breaks the mirror outright. This is a classification,
not a preference — which is why the shift is a *parameter of the rule*
and not a boolean flag, and why the two interesting values are theorems
rather than conventions.

Why the nodes are POINTS, not angles
====================================

:attr:`~orpheus.numerics.measure.DiscreteMeasure.nodes` holds
:math:`(\cos\varphi_m,\, \sin\varphi_m)` — the roots of unity as points
of :math:`S^1 \subset \mathbb{R}^2` — generated by
:func:`~orpheus.numerics.roots_of_unity.roots_of_unity`, never by
evaluating :func:`numpy.cos` on a stored angle.

The reason is exactly the reason that module exists: a node set defined
by a symmetry group must be produced by the group's action. Here it buys
something the campaign specifically needs — :math:`\sin\varphi` is
**exactly** ``0.0`` at the on-axis nodes and exactly non-zero elsewhere,
so :math:`\Sigma = \{\xi = 0\}` is decided by an equality rather than by
a tolerance. ``np.sin(np.pi)`` is ``1.22e-16``; a fold whose singular
set is defined by a tolerance around that is a fold whose well-posedness
condition is a tuning parameter.

The angle chart remains recoverable (:func:`numpy.arctan2` on exact
components is exact at the axis nodes and correctly rounded elsewhere),
so nothing is lost — but it is a chart, chosen by whoever needs one, and
it carries a branch cut that the point representation does not.

See Also
--------
:mod:`orpheus.numerics.roots_of_unity`
    The exact generator; its header carries the measured comparison
    against ``linspace`` + ``cos``.
:mod:`orpheus.numerics.exactness`
    Why a degree without its reference measure is half a claim.
:func:`orpheus.numerics.quadrature.rules_product.product_mu_phi`
    The consumer this rule is built for — the azimuthal factor of the
    sphere product rule, today still welded in as ``linspace``.

References
----------

* Trefethen, L.N. and Weideman, J.A.C. (2014). "The exponentially
  convergent trapezoidal rule." *SIAM Review* **56**(3), 385-458.
  §2 — the aliasing argument of :eq:`periodic-trapezoid-aliasing` and
  the geometric convergence that follows from it for analytic
  integrands.
* Van Loan, C. (1992). *Computational Frameworks for the Fast Fourier
  Transform*. SIAM. §1.4 — generation of the roots of unity by symmetry
  rather than by repeated trigonometric evaluation.
"""

from __future__ import annotations

from fractions import Fraction

import numpy as np

from ..exactness import UNIFORM_ON_CIRCLE, ExactnessClaim
from ..measure import SPACE_CIRCLE, DiscreteMeasure
from ..roots_of_unity import roots_of_unity

#: The two shifts for which the node set is mirror-symmetric — the whole
#: classification, per :eq:`periodic-trapezoid-aliasing`'s discussion.
#: Named because they are theorems about the rule, not conventions: every
#: other shift in :math:`[0,1)` destroys the reflection entirely.
NODE_ALIGNED = Fraction(0)
STAGGERED = Fraction(1, 2)


def periodic_trapezoid(n: int, *, shift: Fraction) -> DiscreteMeasure:
    r"""The :math:`n`-point periodic trapezoid on :math:`S^1`.

    Implements :eq:`periodic-trapezoid`. Nodes are the roots of unity
    :math:`\zeta_{bn}^{\,bm + a}` for :math:`\mathrm{shift} = a/b`, as
    :math:`(\cos, \sin)` pairs generated by the group action; weights are
    :math:`2\pi/n` uniformly, so the mass is the :math:`2\pi` of the
    uniform measure on :math:`S^1`.

    Parameters
    ----------
    n : int
        Number of nodes; must be :math:`\ge 1`.
    shift : Fraction
        The rotation of the node lattice, **in units of one step**
        :math:`2\pi/n`. Reduced modulo :math:`1`, because a full step is
        the same rule with its nodes relabelled — so the parameter space
        is the quotient :math:`\mathbb{Q}/\mathbb{Z}` and
        ``shift=Fraction(5, 2)`` is ``shift=STAGGERED``.

        **Required, with no default**, because the shift is
        exactness-invisible and yet decides :math:`\Sigma` (see the
        module header): a defaulted value is exactly how a parameter
        that no exactness gate can see goes unexamined. Use
        :data:`NODE_ALIGNED` or :data:`STAGGERED` unless you specifically
        want a rule with no mirror symmetry at all.

        **Rational, not real**, because the exactness of the node
        generation rests on integer arithmetic deciding the axis and
        diagonal fixed points. An irrational shift is representable in
        neither this signature nor the mathematics anyone here wants: it
        would break every symmetry the rule has while changing no claim
        it makes.

    Returns
    -------
    DiscreteMeasure
        Nodes shape ``(n, 2)`` holding :math:`(\cos\varphi, \sin\varphi)`,
        weights shape ``(n,)`` summing to :math:`2\pi`, on
        ``support="S^1"``, carrying
        ``ExactnessClaim(UNIFORM_ON_CIRCLE, n - 1)``.

        ``invariance_group`` is deliberately **not** set. The tag's type
        is :class:`~orpheus.numerics.symmetry.SubgroupOfO3` and this
        measure lives in :math:`\mathbb{R}^2`, so any value would be a
        claim about an embedding this rule has not chosen. The group of
        the embedded set is *computed* where the embedding happens — the
        discipline that three false declarations in this package
        (ERR-072, ERR-073, ERR-074) were the argument for.

    Raises
    ------
    ValueError
        If ``n < 1``, or ``shift`` is not a :class:`~fractions.Fraction`.

    Examples
    --------
    The claim names its space, so it cannot be read as the interval
    rule's:

    >>> from fractions import Fraction
    >>> rule = periodic_trapezoid(8, shift=Fraction(1, 2))
    >>> str(rule.exactness)
    'exact to trigonometric degree 7 against uniform(S^1)'

    A staggered even-``n`` rule has no node on the mirror axis, and
    ``0.0`` here is an exact answer rather than a rounded one:

    >>> bool((rule.nodes[:, 1] != 0.0).all())
    True
    >>> float(periodic_trapezoid(8, shift=Fraction(0)).nodes[0, 1])
    0.0
    """
    if n < 1:
        raise ValueError(f"periodic_trapezoid requires n >= 1, got n={n}")
    if not isinstance(shift, Fraction):
        raise ValueError(
            f"periodic_trapezoid requires a Fraction shift, got "
            f"{type(shift).__name__}. The node set is generated by the "
            f"group action on exact rationals; a float shift would be the "
            f"parameterization-evaluation this construction exists to "
            f"avoid. Use Fraction(0) / Fraction(1, 2) — or the named "
            f"NODE_ALIGNED / STAGGERED."
        )

    # The fundamental domain of the shift: one whole step is the identity
    # with the nodes relabelled, so `shift` is an element of Q/Z and this
    # reduction canonicalises the representative rather than restricting
    # the caller.
    step_fraction = shift % 1
    a, b = step_fraction.numerator, step_fraction.denominator

    # phi_m = 2π(m + a/b)/n = 2π(bm + a)/(bn) — a root of unity of order
    # bn, so the whole family is exactly generable however fine the shift.
    cos_phi, sin_phi = roots_of_unity(b * np.arange(n) + a, b * n)

    return DiscreteMeasure(
        nodes=np.column_stack([cos_phi, sin_phi]),
        weights=np.full(n, 2.0 * np.pi / n),
        support=SPACE_CIRCLE,
        # TRIGONOMETRIC degree n-1 against uniform measure on S^1, tight
        # by :eq:`periodic-trapezoid-aliasing` and independent of the
        # shift. Both halves of the claim are needed: the same integer
        # against a polynomial system on an interval would be a
        # different — and, for these nodes, false — statement.
        exactness=ExactnessClaim(reference=UNIFORM_ON_CIRCLE, degree=n - 1),
    )


__all__ = ["NODE_ALIGNED", "STAGGERED", "periodic_trapezoid"]
