"""The two shapes a generated target takes.

A **whole file** is the stamp followed by the rendered text (a rule core, a
skill, the lessons index). A **block** is spliced between ``GENERATED``
markers inside a hand-maintained file (an agent file's role block after its
front matter; the on-boarding block of a harness's root instruction file);
everything outside the markers is kept, and a file that has lost a marker, or
carries the block without its markers, is a problem rather than a duplicate. On
a first run the block is inserted after the file's front matter; a root
instruction file has none, so its markers are placed by hand once.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

GENERATOR = "tools/harness"  # what the stamp names; `python -m tools.harness`
STAMP_PREFIX = "<!-- GENERATED by "
BEGIN_PREFIX = "<!-- BEGIN GENERATED "
_FRONT = re.compile(r"\A---\n.*?\n---\n", re.S)


def stamp(src_rel: str) -> str:
    return (f"{STAMP_PREFIX}{GENERATOR} from {src_rel} — DO NOT EDIT. Edit the source page; "
            f"`python -m {GENERATOR.replace('/', '.')}` (or any Sphinx build) rewrites this file. -->\n")


@dataclass(frozen=True)
class WholeFile:
    text: str


@dataclass(frozen=True)
class Block:
    label: str
    text: str


Rendered = WholeFile | Block


def markers(label: str, src_rel: str) -> tuple[str, str]:
    return (f"{BEGIN_PREFIX}{label} — source: {src_rel}; edit the source, not this block -->",
            f"<!-- END GENERATED {label} -->")


def block_text(block: Block, src_rel: str) -> str:
    """The block as it stands in the file: markers included (what a budget measures)."""
    begin, end = markers(block.label, src_rel)
    return f"{begin}\n{block.text}\n{end}\n"


def splice(block: Block, current: str, src_rel: str, where: str) -> tuple[str, str | None]:
    """``current`` with the block's generated text between its markers, or
    inserted after the front matter on a first run; on a fault, ``current``
    unchanged and the problem, named under ``where``."""
    begin, end = markers(block.label, src_rel)
    generated = block_text(block, src_rel)
    i = current.find(BEGIN_PREFIX + block.label)
    if i >= 0:
        j = current.find(end, i)
        if j < 0:
            return current, f"{where}: BEGIN marker without END"
        tail = current[j + len(end):]
        return current[:i] + generated + (tail[1:] if tail.startswith("\n") else tail), None
    if end in current:
        return current, f"{where}: END marker without BEGIN"
    if block.text.split("\n", 1)[0] in current:  # the source's own H1 line, present without its markers
        return current, (f"{where}: the {block.label} is present without its markers; "
                         "restore the markers or delete the stale block (regenerating would duplicate it)")
    m = _FRONT.match(current)
    if not m:
        return current, f"{where}: no front matter to insert the {block.label} after; place the markers by hand"
    return current[:m.end()] + "\n" + generated + current[m.end():].lstrip("\n"), None
