r"""Exact :math:`q`-th roots of unity — generated by the group action.

A node set **defined by a symmetry group** must be generated by that
group's ACTION — sign flips, coordinate swaps, index arithmetic, all
exact on floats — not by **evaluating a parameterization** of it.
Evaluating :func:`numpy.cos` / :func:`numpy.sin` at symmetric angles
destroys the symmetry to rounding, and no downstream tolerance recovers
it.

This module is the *generating* face of the concept whose *checking*
face is :mod:`orpheus.numerics.symmetry`: that module answers "does this
node set respect group :math:`G`?", this one produces a node set that
does, by construction. A generated set is the natural input to
:meth:`~orpheus.numerics.symmetry.SubgroupOfO3.is_invariant`.

The failure the module exists to remove
=======================================

Every circular node set in the tree sits at an exact **rational**
multiple of :math:`2\pi` — so it is a set of roots of unity, and the
cyclic group :math:`C_q` permutes it. Sampling it as
``np.cos(np.linspace(0, 2*np.pi, q, endpoint=False))`` throws that away:

.. code-block:: text

   cos(pi/2)  = +6.123233995736766e-17      # should be 0
   sin(pi)    = +1.2246467991473532e-16     # should be 0
   cos(3*pi/2) = -1.8369701987210297e-16    # should be 0

:math:`\sin(0)` **is** exactly ``0.0``, which is why the defect is not
even symmetric between the two components — and why it is not stable
under a face flip.

The construction
================

Write :math:`\theta = 2\pi p / q` and split off quarter turns using
**integer** division of :math:`4p` by :math:`q`:

.. math::
   :label: roots-of-unity-quarter-split

   4p = \mathrm{quad}\cdot q + r,
   \qquad
   \theta = \mathrm{quad}\cdot\frac{\pi}{2}
          + \frac{\pi}{2}\cdot\frac{r}{q},
   \qquad 0 \le r < q .

The residual :math:`\varphi = (\pi/2)(r/q)` lies in the first quadrant.
Fold it into the first **octant** with :math:`r \mapsto \min(r,\,q-r)`;
when the fold fires (:math:`2r > q`) the residual is
:math:`\pi/2 - \varphi`, whose cosine and sine are :math:`\varphi`'s
sine and cosine — so undoing the fold is a **coordinate swap**, not an
arithmetic operation. The quarter turns are then applied as **sign
flips**:

.. math::
   :label: roots-of-unity-quadrant

   (\cos, \sin)\big|_{\mathrm{quad}} =
   \begin{cases}
     (+c_0,\, +s_0) & \mathrm{quad} = 0 \\
     (-s_0,\, +c_0) & \mathrm{quad} = 1 \\
     (-c_0,\, -s_0) & \mathrm{quad} = 2 \\
     (+s_0,\, -c_0) & \mathrm{quad} = 3
   \end{cases}

Because the mirror partner :math:`p \mapsto q - p` maps
:math:`(\mathrm{quad},\, r) \mapsto (3 - \mathrm{quad},\, q - r)`, it
lands on the **same** folded residual — hence the same ``theta``, hence
the same two transcendental evaluations — and the quadrant table then
differs only by sign. That is why the mirror is bit-exact rather than
merely accurate: the two partners are not computed independently.

Trig is evaluated on the first octant ONLY. This is the technique FFT
libraries use for twiddle factors, for exactly the same reason.

The two fixed points — decided by integer arithmetic, never a tolerance
=====================================================================

* **The axis** (:math:`4p \equiv 0 \bmod q`): :math:`r = 0` gives
  ``theta == 0.0``, and IEEE-754 makes ``np.cos(0.0)`` exactly ``1.0``
  and ``np.sin(0.0)`` exactly ``0.0``. The axis is therefore exact with
  **no branch of its own** — it falls out of the construction.
* **The 45° diagonal** (:math:`2r = q`): a fixed point of the octant
  swap, so both components must be :math:`\sqrt2/2` — but
  ``np.cos(np.pi/4)`` and ``np.sin(np.pi/4)`` differ by 1 ULP
  (measured: ``1.110e-16``), which would break the swap symmetry at
  precisely the point that defines it. Both components are set to
  ``np.sqrt(0.5)``, the correctly-rounded :math:`\sqrt2/2` (``sqrt`` is
  correctly rounded per IEEE-754 and ``0.5`` is exact).

Signed zero is canonicalised: the quadrant table produces ``-0.0``
wherever a sign flip lands on an exact zero, and ``x + 0.0`` maps
``-0.0`` to ``+0.0`` while being the exact identity on every other
finite value.

Measured properties
===================

Over :math:`q \in \{3,4,5,6,8,10,12,16,20,24,32,48,64\}`, against the
status quo (``np.linspace`` + ``np.cos``/``np.sin``), with each mirror
applied as an **index permutation on the node set** (the only honest
test — ``cos(-x) == cos(x)`` holds for *any* ``x`` because libm's
cosine is even by construction, so negating the angle tests nothing):

.. code-block:: text

   x-mirror  k -> (n-k) mod n  bit-exact:   this module: every q
                                            linspace+cos: NO q
   y-mirror  k -> (n/2 - k)    bit-exact:   this module: every even q
                                            linspace+cos: NO q
   45-diagonal |cos| == |sin|  bit-exact:   this module: every q % 8 == 0
                                            linspace+cos: NO such q

Accuracy is also strictly better, not merely different: against a
100-digit :mod:`mpmath` reference over the same sweep, this construction
is closer to the true value on **312** components and further on **8**.
Node values move by at most ``9.99e-16`` relative to the status quo.

See Also
--------
:mod:`orpheus.numerics.symmetry`
    The checking face — :meth:`~orpheus.numerics.symmetry.SubgroupOfO3.is_invariant`
    verifies that a measure respects a named subgroup of :math:`O(3)`.

References
----------

* Van Loan, C. (1992). *Computational Frameworks for the Fast Fourier
  Transform*. SIAM. §1.4 — twiddle-factor generation by symmetry rather
  than by repeated trigonometric evaluation, the same octant argument.
* Muller, J.-M. et al. (2018). *Handbook of Floating-Point Arithmetic*,
  2nd ed. Birkhäuser. §11 — argument reduction and why evaluating a
  transcendental at a reduced argument beats evaluating it at the
  original.
* Issue #325 and ``.claude/plans/b3_domain_narrowing_crosswalk.md`` §14
  — the ORPHEUS-specific motivation (the boundary trace's three-way
  face partition and the specular reflection partner map).
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

__all__ = ["roots_of_unity"]


# The correctly-rounded sqrt(2)/2, shared by both components at the 45°
# diagonal. NOT np.cos(np.pi / 4) — that differs from np.sin(np.pi / 4)
# by 1 ULP, which would break the octant swap at its own fixed point.
_SQRT_HALF: float = float(np.sqrt(0.5))


def roots_of_unity(
    numerators: NDArray[np.integer] | int,
    denominator: int,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    r"""Cosine and sine of :math:`2\pi p / q`, exact under the dihedral action.

    Returns the real and imaginary parts of :math:`\zeta_q^{\,p}` where
    :math:`\zeta_q = e^{2\pi i / q}`. The node set is generated by the
    group action (:eq:`roots-of-unity-quarter-split`,
    :eq:`roots-of-unity-quadrant`), so its mirror symmetries hold
    **bit-exactly** and its on-axis members are exactly ``0.0`` /
    ``±1.0`` — neither of which survives evaluating
    :func:`numpy.cos` on a :func:`numpy.linspace` of angles.

    Parameters
    ----------
    numerators : array_like of int
        The powers :math:`p`. Reduced mod ``denominator``, so negative
        and out-of-range values are accepted and name the partner they
        should: ``-p`` is the mirror of ``p``. MUST be of integer dtype
        — a float numerator is refused rather than truncated, because
        the whole guarantee rests on the arithmetic being exact.
    denominator : int
        The order :math:`q \ge 1`.

    Returns
    -------
    cos, sin : ndarray of float
        Shape matches ``numerators``. Every component satisfies
        :math:`\cos^2 + \sin^2 = 1` to within 1 ULP, and no component is
        a negative zero.

    Raises
    ------
    ValueError
        If ``denominator < 1``, or ``numerators`` is not of integer
        dtype.

    Examples
    --------
    The four 4th roots of unity are exact, where the parameterized form
    is not:

    >>> import numpy as np
    >>> cos, sin = roots_of_unity(np.arange(4), 4)
    >>> cos
    array([ 1.,  0., -1.,  0.])
    >>> float(np.cos(np.linspace(0, 2 * np.pi, 4, endpoint=False))[1])
    6.123233995736766e-17

    The mirror is an exact index permutation, not an approximate match:

    >>> cos, sin = roots_of_unity(np.arange(12), 12)
    >>> mirror = (12 - np.arange(12)) % 12
    >>> bool(np.array_equal(cos, cos[mirror]) and np.array_equal(sin, -sin[mirror]))
    True
    """
    q = int(denominator)
    if q < 1:
        raise ValueError(
            f"roots_of_unity requires denominator >= 1, got denominator={q}"
        )

    p_in = np.asarray(numerators)
    if not np.issubdtype(p_in.dtype, np.integer):
        raise ValueError(
            f"roots_of_unity requires integer numerators, got dtype "
            f"{p_in.dtype!r}. The exactness guarantee rests on integer "
            f"arithmetic deciding the axis and diagonal fixed points; a "
            f"float numerator would be truncated silently and the node "
            f"would land on the wrong root."
        )
    p = p_in.astype(np.int64) % q

    # Quarter turns by integer division; the residual r/q is a first-QUADRANT
    # angle.  Both quantities are exact — no rounding has happened yet.
    quad, r = np.divmod(4 * p, q)

    # Fold the quadrant residual into the first OCTANT.  Mirror partners
    # (r and q - r) fold to the SAME value, so they share these two
    # transcendental evaluations — which is what makes the mirror bit-exact
    # rather than merely accurate.
    lo = np.minimum(r, q - r)
    theta = np.pi * lo / (2.0 * q)
    cos_oct, sin_oct = np.cos(theta), np.sin(theta)

    # Undo the fold: a coordinate SWAP, not arithmetic.
    swap = 2 * r > q
    cos_quad = np.where(swap, sin_oct, cos_oct)
    sin_quad = np.where(swap, cos_oct, sin_oct)

    # The 45° diagonal is the swap's fixed point, so both components must be
    # the SAME float.  Decided by integer arithmetic (2r == q), never by a
    # tolerance.  (The axis, r == 0, needs no such branch: theta is exactly
    # 0.0 and IEEE-754 gives cos/sin of it as exactly 1.0 / 0.0.)
    diagonal = 2 * r == q
    cos_quad = np.where(diagonal, _SQRT_HALF, cos_quad)
    sin_quad = np.where(diagonal, _SQRT_HALF, sin_quad)

    # Apply the quarter turns as sign flips (:eq:`roots-of-unity-quadrant`).
    quadrants = [quad == 0, quad == 1, quad == 2, quad == 3]
    cos = np.select(quadrants, [cos_quad, -sin_quad, -cos_quad, sin_quad])
    sin = np.select(quadrants, [sin_quad, cos_quad, -sin_quad, -cos_quad])

    # Canonicalise signed zero: a sign flip landing on an exact zero yields
    # -0.0.  Adding +0.0 maps it to +0.0 and is the exact identity elsewhere.
    return cos + 0.0, sin + 0.0
