"""Generate the L0 error-catalogue INDEX from the knowledge graph.

The catalogue's bodies live in exactly one place —
``docs/theory/verification/error_catalog.rst``, one ``.. error-entry::``
per defect. This writes the small *index* that
``.claude/skills/vv-principles/SKILL.md`` injects with ``!cat``, so five
preloading agents get the id list, the titles and the catcher counts
without carrying 374 KB of bodies.

**Derived, never authored.** An authored 79-row index beside 79 entries
would be the twin source this whole move exists to remove, so every row
here comes from the graph: the ids and titles from the directives, the
catcher counts from the ``catches`` edges nexus writes out of
``@pytest.mark.catches``. Editing this file by hand is therefore a
no-op — the next build overwrites it.

Why a separate tool from ``generate_matrix.py``, which used to carry an
ERR table: the V&V matrix is a statement about the *test registry*, and
the error catalogue is a record of *defects that happened in this
codebase*. Two concepts. The execution is consolidated (both are rows in
``docs/conf.py``'s ``_GENERATORS``); the concepts are not.

⚠ This one reads the graph, so it runs at ``build-finished`` — nexus
writes ``graph.db`` there, and a ``builder-inited`` hook would read the
PREVIOUS build's graph.

**The dormant column** (#506, ``.claude/plans/reference_p0_spec.md`` §3.2
item 6). The graph counts a ``catches`` edge whatever the test's other
markers are, so a catcher marked ``@pytest.mark.withdrawn`` (skipped by
default) still reads as coverage there. Until sphinxcontrib-nexus records
``withdrawn`` itself, the index reads the RUNNING/WITHDRAWN split from the
audit payload that ``generate_matrix`` persisted earlier in the same build
(:data:`tests._harness.audit.AUDIT_SNAPSHOT`; one collection per build,
never two; a snapshot stamped from another tree is refused) and marks an entry whose every catcher is withdrawn as
dormant, naming the withdrawal issue.

Usage::

    python -m tools.verification.generate_error_index            # write
    python -m tools.verification.generate_error_index --check    # verify
"""

from __future__ import annotations

import sys
from pathlib import Path

from tests._harness.audit import StaleAuditSnapshot, read_audit_snapshot

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DB = REPO_ROOT / ".nexus" / "graph.db"
OUT_PATH = REPO_ROOT / ".claude" / "skills" / "vv-principles" / "error_index.md"
CORPUS_PAGE = "docs/theory/verification/error_catalog.rst"

#: Titles run to ~490 characters (the newest entries are abstracts).
#: The index truncates rather than the source being shortened — that
#: would be a per-entry judgement pass, and the full entry is one grep
#: away regardless.
TITLE_WIDTH = 96


def _truncate(text: str, width: int = TITLE_WIDTH) -> str:
    text = " ".join(text.split())
    if len(text) <= width:
        return text
    return text[: width - 1].rstrip() + "…"


def dormant_entries(payload: dict | None) -> dict[str, list[int]] | None:
    """``ERR-NNN -> [withdrawal issues]`` for every entry whose catchers are
    ALL withdrawn — the audit's ``dormant_errors``; ``None`` when there is
    no payload (a build that did not run ``generate_matrix``)."""
    return None if payload is None else payload["dormant_errors"]


def render(result, dormant: dict[str, list[int]] | None = None) -> str:
    """The index, from an ``ErrorsResult`` and the dormant map
    (:func:`dormant_entries`; ``None`` when no audit snapshot exists)."""
    entries = sorted(result.entries, key=lambda e: e.name)
    uncaught = [e for e in entries if not e.catcher_count]
    known_dormant = dormant or {}
    next_id = "ERR-%03d" % (
        max((int(e.name.split("-")[1]) for e in entries if "-" in e.name),
            default=0) + 1
    )

    out: list[str] = [
        "<!-- GENERATED by tools/verification/generate_error_index.py — DO NOT EDIT.",
        "     Rewritten from the knowledge graph on every Sphinx build. -->",
        "",
        "# L0 error catalogue — index",
        "",
        f"**{result.total_entries} entries · {result.total_catchers} catching "
        f"tests · {len(uncaught)} uncaught"
        + (f" · {len(known_dormant)} dormant.**" if dormant is not None
           else ".** (dormant status unavailable: no audit snapshot; build "
                "the docs.)"),
        "",
        "Bodies live once, in the corpus. This index is derived from the graph;",
        "editing it by hand is a no-op.",
        "",
        "## Retrieving an entry",
        "",
        f"Each entry is a graph node whose id is `vv:error:<ID>` — so ERR-009 is",
        "`vv:error:ERR-009`. State that once here so no reader has to invent the",
        "prefix.",
        "",
        "- **by grep** — `grep -A 40 'error-entry:: ERR-009' "
        f"{CORPUS_PAGE}`",
        "- **by nexus** — `context('vv:error:ERR-009')` for the entry and every",
        "  test that catches it; `errors()` for this table, live.",
        "",
        "## Adding an entry",
        "",
        f"Append a `.. error-entry:: {next_id}` block to `{CORPUS_PAGE}` "
        "(next free id),",
        "then tag its regression test `@pytest.mark.catches(\"" + next_id + "\")`.",
        "A marker naming an id with no entry warns and resolves to nothing; a",
        "`-W` build refuses it.",
        "",
    ]

    if uncaught:
        out += [
            "## ⛔ Uncaught — no test claims these",
            "",
            "A catalogued defect nothing pins is an unguarded regression.",
            "",
        ]
        out += [f"- **{e.name}** — {_truncate(e.title)}" for e in uncaught]
        out.append("")
    else:
        out += [
            "## Uncaught",
            "",
            "None — every catalogued defect has at least one catching test.",
            "",
        ]

    if known_dormant:
        out += [
            "## Dormant — every catcher is withdrawn",
            "",
            "Each catcher is marked `@pytest.mark.withdrawn` and skipped by",
            "default, so the catcher count below is a claim nothing currently",
            "runs. The entry returns to coverage when its withdrawal issue",
            "closes (or run it with `ORPHEUS_RUN_WITHDRAWN=<issue>`).",
            "",
        ]
        out += [
            f"- **{err}** — withdrawn under "
            + ", ".join(f"#{n}" for n in issues)
            for err, issues in sorted(known_dormant.items())
        ]
        out.append("")

    out += [
        "## The catalogue",
        "",
        "| id | catchers | dormant | title |",
        "|---|---:|---|---|",
    ]
    for e in entries:
        title = _truncate(e.title).replace("|", "\\|")
        status = " ".join(f"#{n}" for n in known_dormant.get(e.name, ()))
        out.append(f"| {e.name} | {e.catcher_count} | {status} | {title} |")
    out.append("")
    return "\n".join(out)


def _load_result(db: Path):
    from sphinxcontrib.nexus.export import load_sqlite
    from sphinxcontrib.nexus.query import GraphQuery

    return GraphQuery(load_sqlite(db).nxgraph).errors(max_catchers_per_entry=0)


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    check_mode = "--check" in argv
    db = DEFAULT_DB

    if not db.is_file():
        # An absence must say where it looked. Not an error: a fresh
        # clone has no graph, and the tracked index is still valid.
        print(f"no graph at {db} — index left as-is "
              "(build the docs to refresh it)")
        return 0

    result = _load_result(db)
    if not result.total_entries:
        print(f"graph at {db} declares no `.. error-entry::` — "
              f"index left as-is ({len(result.unresolved_markers)} marker "
              "id(s) resolve to nothing)")
        return 0

    try:
        snapshot = read_audit_snapshot()
    except StaleAuditSnapshot as exc:
        print(f"error-catalogue index NOT written: {exc}", file=sys.stderr)
        return 1
    rendered = render(result, dormant_entries(snapshot))

    if check_mode:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.is_file() else ""
        if current != rendered:
            print(
                f"{OUT_PATH.relative_to(REPO_ROOT)} is STALE — regenerate with"
                " `python -m tools.verification.generate_error_index`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT_PATH.relative_to(REPO_ROOT)} is up to date "
              f"({result.total_entries} entries)")
        return 0

    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} "
          f"({result.total_entries} entries, {result.total_catchers} catchers, "
          f"{result.uncaught} uncaught)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
