"""Generate the F_N method capability-matrix include file.

Emits ``docs/theory/_fn_method_capability_matrix.inc.rst``, an RST
fragment ``.. include::``'d by ``docs/theory/fn_method.rst`` at the
"Capabilities at a glance" section.

The data is the **single source of truth** for which F_N method
references are shipped: it is pulled from
:func:`orpheus.derivations.continuous.fn_method.cases.capability_rows`,
the metadata-only function the matrix infrastructure discovers.

This is an **interim per-method generator**. It mirrors
:mod:`tools.verification.generate_peierls_nystrom_matrix`. A
forthcoming meta-generator
(:mod:`tools.verification.generate_capability_matrices`) auto-discovers
``cases.py:capability_rows()`` across every package in
``orpheus.derivations.continuous`` and replaces both per-method
generators with a single tool.

Usage::

    python -m tools.verification.generate_fn_method_matrix [OUT_RST]

``OUT_RST`` defaults to ``docs/theory/_fn_method_capability_matrix.inc.rst``.

See also
--------
:mod:`tools.verification.generate_peierls_nystrom_matrix`
    Sibling per-method generator for the peierls_nystrom package.
:mod:`tools.verification.generate_matrix`
    Sphinx V&V matrix generator (different output: pytest registry,
    not capability matrix).
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "docs" / "theory" / "_fn_method_capability_matrix.inc.rst"


_GEOM_LABELS = {
    "infinite": "infinite",
    "slab": "slab",
    "cylinder-1d": "cylinder-1d",
    "sphere-1d": "sphere-1d",
}


def _list_table(
    title: str,
    headers: list[str],
    widths: list[int],
    rows: list[list[str]],
) -> str:
    """Render a ``.. list-table::`` block.

    Mirrors the helper in ``generate_peierls_nystrom_matrix.py`` —
    the meta-generator will absorb the duplication.
    """
    if len(headers) != len(widths):
        raise ValueError(
            f"header/width count mismatch: "
            f"{len(headers)} headers vs {len(widths)} widths"
        )
    lines: list[str] = []
    lines.append(f".. list-table:: {title}")
    lines.append("   :header-rows: 1")
    lines.append(f"   :widths: {' '.join(str(w) for w in widths)}")
    lines.append("")
    lines.append(f"   * - {headers[0]}")
    for h in headers[1:]:
        lines.append(f"     - {h}")
    for row in rows:
        if len(row) != len(headers):
            raise ValueError(
                f"row/header count mismatch: row={row!r}, "
                f"headers={headers!r}"
            )
        lines.append(f"   * - {row[0]}")
        for cell in row[1:]:
            lines.append(f"     - {cell}")
    lines.append("")
    return "\n".join(lines)


def _render(rows: list[dict]) -> str:
    """Render the full include file from the metadata rows."""
    lines: list[str] = []
    lines.append(
        "..\n"
        "   AUTO-GENERATED by "
        "``tools/verification/generate_fn_method_matrix.py``.\n"
        "   Do not edit by hand — changes will be overwritten on the\n"
        "   next Sphinx build. The single source of truth is\n"
        "   ``orpheus.derivations.continuous.fn_method.cases.capability_rows()``.\n"
    )
    lines.append("")

    headers = [
        "Reference name",
        "Geometry",
        "n_g",
        "n_reg",
        "BC",
        "Status",
        "Accuracy class",
    ]
    widths = [38, 12, 6, 6, 16, 30, 22]

    data_rows = []
    for r in rows:
        data_rows.append([
            str(r["name"]),
            _GEOM_LABELS.get(str(r["geometry"]), str(r["geometry"])),
            str(r["n_groups"]),
            str(r["n_regions"]),
            str(r["bc"]),
            str(r["status"]),
            str(r.get("accuracy", "—")),
        ])

    lines.append(
        _list_table(
            title=(
                "Shipped F_N method continuous references "
                "(Sood/LA-13511 + Neshat-Maiorino 1980)"
            ),
            headers=headers,
            widths=widths,
            rows=data_rows,
        )
    )

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    out_path = Path(argv[0]) if argv else DEFAULT_OUT
    out_path.parent.mkdir(parents=True, exist_ok=True)

    from orpheus.derivations.continuous.fn_method.cases import capability_rows

    rows = capability_rows()
    rst = _render(rows)
    out_path.write_text(rst, encoding="utf-8")
    print(
        f"wrote {out_path.relative_to(REPO_ROOT)} "
        f"({len(rows)} F_N method capability rows)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
